Description of chir
chir
PURPOSE
CHIR Chi squared random numbers
SYNOPSIS
function r=chir(m,n,df)
DESCRIPTION
CHIR    Chi squared random numbers
 usage: chir(m,n,df), m,n shape of the result, df degrees of freedom
CROSS-REFERENCE INFORMATION
This function calls:
gammar GAMMAR random deviates from gamma distribution
gammar GAMMAR random deviates from gamma distribution
This function is called by:
betar BETAR Beta random numbers
chi1r CHI1R(m,n,df) chi random numbers
fr FR Random numbers from the F distribution
invchir INVCHIR(m,n,N0,S2) inverse scaled chi squared random numbers
mvtr MVTR Multivariate t random variates
tr TR Random numbers from the t distribution
wishr WISHR Random matrix from Wishart distribution
betar BETAR Beta random numbers
chi1r CHI1R(m,n,df) chi random numbers
fr FR Random numbers from the F distribution
invchir INVCHIR(m,n,N0,S2) inverse scaled chi squared random numbers
mvtr MVTR Multivariate t random variates
tr TR Random numbers from the t distribution
wishr WISHR Random matrix from Wishart distribution
SOURCE CODE
function r=chir(m,n,df)
%CHIR    Chi squared random numbers
% usage: chir(m,n,df), m,n shape of the result, df degrees of freedom
% Marko Laine <marko.laine@fmi.fi>
% $Revision: 1.5 $  $Date: 2012/09/27 11:47:34 $
r = gammar(m,n,df/2,2);