Description of gammapf
gammapf
PURPOSE
GAMMAPF - gamma probability density function
SYNOPSIS
function y=gammapf(x,a,b)
DESCRIPTION
 GAMMAPF - gamma probability density function
 GAMMAPF(x,a,b) x quantile, a shape, b scale
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
chi1pf CHI1PF Chi probability density function
chipf CHIPF Chi squared probability density function
density DENSITY Density estimator using Gaussian kernel
chi1pf CHI1PF Chi probability density function
chipf CHIPF Chi squared probability density function
density DENSITY Density estimator using Gaussian kernel
SOURCE CODE
function y=gammapf(x,a,b)
% GAMMAPF - gamma probability density function
% GAMMAPF(x,a,b) x quantile, a shape, b scale
% huom parametrisointi
% Marko Laine <marko.laine@fmi.fi>
% $Revision: 1.4 $  $Date: 2012/09/27 11:47:36 $
if nargin<2, a=1; end
if nargin<3, b=1; end
%y = b.^(-a) ./ gamma(a) .* x.^(a-1) .* exp(-x./b);
y = exp(-a*log(b)-gammaln(a)+(a-1)*log(x)-x./b);