Description of geweke
geweke
PURPOSE
GEWEKE Geweke's MCMC convergence diagnostic
SYNOPSIS
function [z,p]=geweke(chain,a,b)
DESCRIPTION
GEWEKE Geweke's MCMC convergence diagnostic
 [z,p] = geweke(chain,a,b)
 Test for equality of the means of the first a% (default 10%) and
 last b% (50%) of a Markov chain.
 See:
 Stephen P. Brooks and Gareth O. Roberts.
 Assessing convergence of Markov chain Monte Carlo algorithms.
 Statistics and Computing, 8:319--335, 1998.
CROSS-REFERENCE INFORMATION
This function calls:
nordf NORDF the standard normal (Gaussian) cumulative distribution.
spectrum0 SPECTRUM0 Spectral density at frequency zero
nordf NORDF the standard normal (Gaussian) cumulative distribution.
spectrum0 SPECTRUM0 Spectral density at frequency zero
This function is called by:
chainstats CHAINSTATS some statistics from the MCMC chain
gewekeplot GEWEKEPLOT Plot Geweke's diagnostic
mcmcrun MCMCRUN Metropolis-Hastings MCMC simulation for nonlinear Gaussian models
mcmcrun_compile MCMCRUN Metropolis-Hastings MCMC simulation for nonlinear Gaussian models
chainstats CHAINSTATS some statistics from the MCMC chain
gewekeplot GEWEKEPLOT Plot Geweke's diagnostic
mcmcrun MCMCRUN Metropolis-Hastings MCMC simulation for nonlinear Gaussian models
SOURCE CODE
function [z,p]=geweke(chain,a,b)
%GEWEKE Geweke's MCMC convergence diagnostic
% [z,p] = geweke(chain,a,b)
% Test for equality of the means of the first a% (default 10%) and
% last b% (50%) of a Markov chain.
% See:
% Stephen P. Brooks and Gareth O. Roberts.
% Assessing convergence of Markov chain Monte Carlo algorithms.
% Statistics and Computing, 8:319--335, 1998.
% ML, 2002
% $Revision: 1.3 $  $Date: 2003/05/07 12:22:19 $
[nsimu,npar]=size(chain);
if nargin<3
  a = 0.1;
  b = 0.5;
end
na = floor(a*nsimu);
nb = nsimu-floor(b*nsimu)+1;
if (na+nb)/nsimu >= 1
  error('Error with na and nb');
end
m1 = mean(chain(1:na,:));
m2 = mean(chain(nb:end,:));
%%% Spectral estimates for variance
sa = spectrum0(chain(1:na,:));
sb = spectrum0(chain(nb:end,:));
z = (m1-m2)./(sqrt(sa/na+sb/(nsimu-nb+1)));
p = 2*(1-nordf(abs(z)));