Description of nordf
nordf
PURPOSE
NORDF the standard normal (Gaussian) cumulative distribution.
SYNOPSIS
function y=nordf(x,mu,sigma2)
DESCRIPTION
 NORDF the standard normal (Gaussian) cumulative distribution.
 NORPF(x,mu,sigma2) x quantile, mu mean, sigma2 variance
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
beetleex %
beetless Beatle mortality example binomial -2*log(likelihood) function
geweke GEWEKE Geweke's MCMC convergence diagnostic
lognordf LOGNORDF Lognormal cumulative distribution
mcmcplot MCMCPLOT Plot mcmc chain
geweke GEWEKE Geweke's MCMC convergence diagnostic
lognordf LOGNORDF Lognormal cumulative distribution
mcmcplot MCMCPLOT Plot mcmc chain
SOURCE CODE
function y=nordf(x,mu,sigma2)
% NORDF the standard normal (Gaussian) cumulative distribution.
% NORPF(x,mu,sigma2) x quantile, mu mean, sigma2 variance
% Marko Laine <marko.laine@fmi.fi>
% $Revision: 1.6 $  $Date: 2012/09/27 11:47:38 $
if nargin < 2, mu     = 0; end
if nargin < 3, sigma2 = 1; end
%y = 0.5*erf(-Inf,sqrt(2)*0.5*x);
y = 0.5+0.5*erf((x-mu)/sqrt(sigma2)/sqrt(2));