Description of plims
plims
PURPOSE
PLIMS Empirical quantiles
SYNOPSIS
function y=plims(x,p)
DESCRIPTION
PLIMS Empirical quantiles
 plims(x,p)  calculates p quantiles from columns of x
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
chainstats CHAINSTATS some statistics from the MCMC chain
mcmcpred MCMCPRED predictive calculations from the mcmcrun chain
mcmcpred_compile MCMCPRED predictive calculations from the mcmcrun chain
psrf PSRF Gelman-Rubin-Brooks psrf MCMC convergence diagnostic
qqnor QQNOR Q - Q plot for normality.
qqplot QQPLOT quantile - quantile plot
chainstats CHAINSTATS some statistics from the MCMC chain
mcmcpred MCMCPRED predictive calculations from the mcmcrun chain
psrf PSRF Gelman-Rubin-Brooks psrf MCMC convergence diagnostic
qqnor QQNOR Q - Q plot for normality.
qqplot QQPLOT quantile - quantile plot
SOURCE CODE
function y=plims(x,p)
%PLIMS Empirical quantiles
% plims(x,p)  calculates p quantiles from columns of x
% Marko Laine <marko.laine@fmi.fi>
% $Revision: 1.5 $  $Date: 2012/09/27 11:47:39 $
if nargin<2
%  p = [0.025,0.975];
   p = [0.25,0.5,0.75];
end
[n,m] = size(x); if n==1; n=m;end
y = interp1(sort(x),(n-1)*p+1);