Description of xyplot
xyplot
PURPOSE
XYPLOT Plot two first columns of a matrix
SYNOPSIS
function h=xyplot(xy,varargin)
DESCRIPTION
XYPLOT  Plot two first columns of a matrix
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
bananaex %
hist2d HIST2D 2d smoothed histogram calculations
hist2d HIST2D 2d smoothed histogram calculations
SOURCE CODE
function h=xyplot(xy,varargin)
%XYPLOT  Plot two first columns of a matrix
% Marko Laine <marko.laine@fmi.fi>
% $Revision: 1.4 $  $Date: 2012/09/27 11:47:40 $
if nargin>1
   hdl=plot(xy(:,1),xy(:,2),varargin{:});
else
   hdl=plot(xy(:,1),xy(:,2),'.');
end
if nargout>0
   h=hdl;
end