Description of averageReflectivity
averageReflectivity
PURPOSE
Calculates the avereaged reflectivity for domains samples (incoherent
SYNOPSIS
function [totReflect,totSimul] = averageReflectivity(reflect1,reflect2,Simul1,Simul2,domainRatio)
DESCRIPTION
 Calculates the avereaged reflectivity for domains samples (incoherent
 sum)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
domainsTFCustomLayersParallelContrasts Single threaded version of the custom layers, domainsTF reflectivity
domainsTFCustomLayersParallelPoints Single threaded version of the custom layers, domainsTF reflectivity
domainsTFCustomLayersSingle Single threaded version of the custom layers, domainsTF reflectivity
domainsTFCustomXYParallelContrasts Extract individual cell arrays
domainsTFCustomXYParallelPoints Extract individual cell arrays
domainsTFCustomXYSingle Extract individual cell arrays
domainsTFStandardLayersParallelContrasts Single threaded version of the Standard Layers calculation
domainsTFStandardLayersParallelPoints Single threaded version of the Standard Layers calculation
domainsTFStandardLayersSingle Single threaded version of the Standard Layers calculation
SOURCE CODE
function [totReflect,totSimul] = averageReflectivity(reflect1,reflect2,Simul1,Simul2,domainRatio)
% Calculates the avereaged reflectivity for domains samples (incoherent
% sum)
refY1 = reflect1(:,2);
refY2 = reflect2(:,2);
simY1 = Simul1(:,2);
simY2 = Simul2(:,2);
averageRefY = (domainRatio * refY1) + ((1 - domainRatio) * refY2);
averageSimY = (domainRatio * simY1) + ((1 - domainRatio) * simY2);
totReflect = [reflect1(:,1) averageRefY(:)];
totSimul = [Simul1(:,1) averageSimY(:)];
end