m2html('mfiles',{'./targetFunctions','./API'},'htmldir','m2htmlGeneratedDocs', 'recursive','on',... 
'global','on','template','frame', 'index','menu','ignoredDir',{'docs','Docs_old','tests','testSuite'},...
'graph','on','source','on');