Description of standardTF_custlay_single
standardTF_custlay_single
PURPOSE
Single threaded version of the custom layers, standardTF reflectivity
SYNOPSIS
function [outSsubs,backgs,qshifts,sfs,nbas,nbss,resols,chis,reflectivity,Simulation,shifted_data,layerSlds,sldProfiles,allLayers,allRoughs] = standardTF_custlay_single(problemDef,problemDef_cells,problemDef_limits,controls)
DESCRIPTION
 Single threaded version of the custom layers, standardTF reflectivity
 calculation. The function extracts the relevant parameters from the input
 arrays, allocates these on a pre-contrast basis, then calls the 'core'
 calculation (the core layers standardTf calc is shared between multiple
 calculation types).
CROSS-REFERENCE INFORMATION
This function calls:
RAT_parse_cells Splits up the master input list of all arrays into separate arrays
extractProblemParams Extract individual parameters from problemDef
backSort Distributes the background and shift values among the different contrasts
loopCppCustlayWrapper_CustLaysingle
loopMatalbCustlayWrapper_CustLaysingle #codegen
loopMatalbCustlayWrapper_CustLaysingle #codegen
standardTF_layers_core This is the main reflectivity calculation for all Layers models in the
This function is called by:
standardTF_custLay_reflectivityCalculation Custom layers reflectivity calculation for standardTF
SOURCE CODE
function [outSsubs,backgs,qshifts,sfs,nbas,nbss,resols,chis,reflectivity,...
    Simulation,shifted_data,layerSlds,sldProfiles,allLayers,...
    allRoughs] = standardTF_custlay_single(problemDef,problemDef_cells,...
    problemDef_limits,controls)
% Single threaded version of the custom layers, standardTF reflectivity
% calculation. The function extracts the relevant parameters from the input
% arrays, allocates these on a pre-contrast basis, then calls the 'core'
% calculation (the core layers standardTf calc is shared between multiple
% calculation types).
% Extract individual cell arrays
[repeatLayers,...
 allData,...
 dataLimits,...
 simLimits,...
 contrastLayers,...
 layersDetails...
 customFiles] = RAT_parse_cells(problemDef_cells);
% Extract individual parameters from problemDef struct
[numberOfContrasts, geometry, cBacks, cShifts, cScales, cNbas, cNbss,...
cRes, backs, shifts, sf, nba, nbs, res, dataPresent, nParams, params,...
numberOfLayers, resample, backsType, cCustFiles] =  extractProblemParams(problemDef);
calcSld = controls.calcSld;
% Pre-Allocation of output arrays...
backgs = zeros(numberOfContrasts,1);
qshifts = zeros(numberOfContrasts,1);
sfs = zeros(numberOfContrasts,1);
nbas = zeros(numberOfContrasts,1);
nbss = zeros(numberOfContrasts,1);
resols = zeros(numberOfContrasts,1);
allRoughs = zeros(numberOfContrasts,1);
outSsubs = zeros(numberOfContrasts,1);
chis =  zeros(numberOfContrasts,1);
allLayers = cell(numberOfContrasts,1);
layerSlds = cell(numberOfContrasts,1);
sldProfiles = cell(numberOfContrasts,1);
shifted_data = cell(numberOfContrasts,1);
reflectivity = cell(numberOfContrasts,1);
for i = 1:numberOfContrasts
    reflectivity{i} = [1 1 ; 1 1];
end
Simulation = cell(numberOfContrasts,1);
for i = 1:numberOfContrasts
    Simulation{i} = [1 1 ; 1 1];
end
allLayers = cell(numberOfContrasts,1);
for i = 1:numberOfContrasts
    allLayers{i} = [1 ; 1];
end
%   --- End Memory Allocation ---
% Resampling parameters
resamPars = controls.resamPars;
% Depending on custom layer language we change the functions used
lang = customFiles{1}{2}; % so if there are multiple language models we should have a variable that seeks what language model is being used
switch lang
case 'matlab'
    % Call the Matlab parallel loop to process the custom models.....
    [allLayers, allRoughs] = loopMatalbCustlayWrapper_CustLaysingle(cBacks,cShifts,cScales,cNbas,cNbss,cRes,backs,...
    shifts,sf,nba,nbs,res,cCustFiles,numberOfContrasts,customFiles,params);
case 'cpp'
    [allLayers,allRoughs] = loopCppCustlayWrapper_CustLaysingle(cBacks,cShifts,cScales,cNbas,cNbss,cRes,backs,...
    shifts,sf,nba,nbs,res,cCustFiles,numberOfContrasts,customFiles,params);
end
% Single cored over all contrasts
for i = 1:numberOfContrasts
    % Extract the relevant parameter values for this contrast
    % from the input arrays.
    % First need to decide which values of the backrounds, scalefactors
    % data shifts and bulk contrasts are associated with this contrast
    [thisBackground,thisQshift,thisSf,thisNba,thisNbs,thisResol] = backSort(cBacks(i),cShifts(i),cScales(i),cNbas(i),cNbss(i),cRes(i),backs,shifts,sf,nba,nbs,res);
    % Get the custom layers output for this contrast
    thisContrastLayers = allLayers{i};
    % For the other parameters, we extract the correct ones from the input
    % arrays
    thisRough = allRoughs(i);
    thisRepeatLayers = repeatLayers{i};
    thisResample = resample(i);
    thisCalcSld = calcSld;
    thisData = allData{i};
    thisDataPresent = dataPresent(i);
    thisDataLimits = dataLimits{i};
    thisSimLimits = simLimits{i};
    thisBacksType = backsType(i);
    % Now call the core standardTF_stanlay reflectivity calculation
    % In this case we are single cored, so we do not parallelise over
    % points
    paralellPoints = 'single';
    % Call the reflectivity calculation
    [sldProfile,reflect,Simul,shifted_dat,layerSld,resamLayers,thisChiSquared,thisSsubs] = ...
    standardTF_layers_core...
    (thisContrastLayers, thisRough, ...
    geometry, thisNba, thisNbs, thisResample, thisCalcSld, thisSf, thisQshift,...
    thisDataPresent, thisData, thisDataLimits, thisSimLimits, thisRepeatLayers,...
    thisBackground,thisResol,thisBacksType,nParams,paralellPoints,resamPars);
    % Store returned values for this contrast in the output arrays.
    % As well as the calculated profiles, we also store a record of
    % the other values (background, scalefactors etc) for each contrast
    % for future use.
    outSsubs(i) = thisSsubs;
    sldProfiles{i} = sldProfile;
    reflectivity{i} = reflect;
    Simulation{i} = Simul;
    shifted_data{i} = shifted_dat;
    layerSlds{i} = layerSld;
    allLayers{i} = resamLayers;
    chis(i) = thisChiSquared;
    backgs(i) = thisBackground;
    qshifts(i) = thisQshift;
    sfs(i) = thisSf;
    nbas(i) = thisNba;
    nbss(i) = thisNbs;
    resols(i) = thisResol;
    allRoughs(i) = thisRough;
end
end