Description of backSort
backSort
PURPOSE
Distributes the background and shift values among the different contrasts
SYNOPSIS
function [outBackground,outQzshift,outScalefactor,outBulkIn,outBulkOut,outResolution] = backSort(contrastBackgrounds,contrastQzshifts,contrastScalefactors,contrastBulkIns,contrastBulkOuts,contrastResolutions,backs,qzshifts,scalefactor,bulkIn,bulkOut,res)
DESCRIPTION
 Distributes the background and shift values among the different contrasts
 USAGE::
    [backg,qzshift,scalefactor,bulkIn,bulkOut,resol] = backsort(contrastBackgrounds,contrastQzshifts,contrastScalefactors,contrastBulkIns,contrastBulkOuts,contrastResolutions,backs,shifts,scalefactor,bulkIn,bulkOut,res)
 INPUTS:
    * contrastBackgrounds: Which background value is associated with each contrast
    * contrastQzshifts: Which qz_shift value is associated with each contrast
    * contrastScalefactors: Which scalefactor value is associated with each contrast
    * contrastBulkIns: Which BulkIn value is associated with each contrast
    * contrastBulkOuts: Which BulkOut value is associated with each contrast
    * contrastResolutions: Which resolution value is associated with each contrast
    * backs: List of all background values.
    * shifts: List of all qzshift values
    * scalefactor: List of all scalefactor values
    * bulkIn: List of all bulkIn values
    * bulkOut: List of all bulkOut values
    * res: List of all resolution values
 OUTPUTS:
    * outBackground: list of actual background values for each contrast
    * outQzshift: list of actual qzshift values for each contrast
    * outScalefactor: list of actual scalefactor values for each contrast
    * outBulkIn: list of actual bulkIn values for each contrast
    * outBulkOut: list of actual bulkOut values for each contrast
    * outResolution: list of actual resolution for each contrast
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
parallelContrasts Single threaded version of the custom layers, domainsTF reflectivity
parallelPoints Single threaded version of the custom layers, domainsTF reflectivity
processCustomFunction Top-level function for processing custom layers for all the
single Single threaded version of the custom layers, domainsTF reflectivity
parallelContrasts Extract individual cell arrays
parallelPoints Extract individual cell arrays
processCustomFunction Top-level function for processing custom XY profiles for all the
single Extract individual cell arrays
parallelContrasts Single threaded version of the Standard Layers calculation
parallelPoints Single threaded version of the Standard Layers calculation
single Single threaded version of the Standard Layers calculation
parallelContrasts Multi threaded version of the custom layers, nonPolarisedTF reflectivity
parallelPoints Multi threaded version of the custom layers over reflectivity poimnts
processCustomFunction Top-level function for processing custom layers for all the
single Single threaded version of the custom layers, nonPolarisedTF reflectivity
parallelContrasts Extract individual cell arrays
parallelPoints Multi threaded version of the custom XY profile over reflectivity points
processCustomFunction Top-level function for processing custom XY profiles for all the
single Extract individual cell arrays
parallelContrasts Standard Layers calculation paralelised over the outer loop
parallelPoints Standard Layers calculation paralelised over the inner loop
single Single threaded version of the Standard Layers calculation
SOURCE CODE
function [outBackground,outQzshift,outScalefactor,outBulkIn,outBulkOut,outResolution] = backSort(contrastBackgrounds,contrastQzshifts,contrastScalefactors,contrastBulkIns,contrastBulkOuts,contrastResolutions,backs,qzshifts,scalefactor,bulkIn,bulkOut,res)
    % Distributes the background and shift values among the different contrasts
    %
    % USAGE::
    %
    %    [backg,qzshift,scalefactor,bulkIn,bulkOut,resol] = backsort(contrastBackgrounds,contrastQzshifts,contrastScalefactors,contrastBulkIns,contrastBulkOuts,contrastResolutions,backs,shifts,scalefactor,bulkIn,bulkOut,res)
    %
    % INPUTS:
    %    * contrastBackgrounds: Which background value is associated with each contrast
    %    * contrastQzshifts: Which qz_shift value is associated with each contrast
    %    * contrastScalefactors: Which scalefactor value is associated with each contrast
    %    * contrastBulkIns: Which BulkIn value is associated with each contrast
    %    * contrastBulkOuts: Which BulkOut value is associated with each contrast
    %    * contrastResolutions: Which resolution value is associated with each contrast
    %    * backs: List of all background values.
    %    * shifts: List of all qzshift values
    %    * scalefactor: List of all scalefactor values
    %    * bulkIn: List of all bulkIn values
    %    * bulkOut: List of all bulkOut values
    %    * res: List of all resolution values
    %
    % OUTPUTS:
    %    * outBackground: list of actual background values for each contrast
    %    * outQzshift: list of actual qzshift values for each contrast
    %    * outScalefactor: list of actual scalefactor values for each contrast
    %    * outBulkIn: list of actual bulkIn values for each contrast
    %    * outBulkOut: list of actual bulkOut values for each contrast
    %    * outResolution: list of actual resolution for each contrast
        %for i = 1:nc
        %thisBack = contrastBackgrounds(i);
        outBackground = backs(contrastBackgrounds);
        %thisShift = contrastQzshifts(i);
        outQzshift = qzshifts(contrastQzshifts);
        %thisScale = contrastScalefactors(i);
        outScalefactor = scalefactor(contrastScalefactors);
        %thisBulkIn = contrastBulkIns(i);
        outBulkIn = bulkIn(contrastBulkIns);
        %thisBulkOut = contrastBulkOuts(i);
        outBulkOut = bulkOut(contrastBulkOuts);
        %thisResol = contrastResolutions(i);
        if contrastResolutions ~= -1
            outResolution = res(contrastResolutions);
        else
            outResolution = -1;     % Negative value means we have a data resolution..
        end
        %end
end