function [background,resolution,shiftedData,simulationXData,dataIndices...
    ] = setupCoreReflectivityCalculation(backgroundParamIndex,...
    resolutionParamIndex,backgroundParams,resolutionParams,qzshift,...
    scalefactor,dataPresent,data,dataLimits,simulationLimits,...
    backgroundType,resolutionType,customFiles,numSimulationPoints)
   
    % Apply scale factors and q shifts to the data
    shiftedData = shiftData(scalefactor,qzshift,dataPresent,data,dataLimits,simulationLimits,numSimulationPoints);
    
    [simulationXData, dataIndices] = makeSimulationRange(shiftedData, simulationLimits);

    background = constructBackground(backgroundType,backgroundParamIndex,...
        shiftedData,customFiles,backgroundParams,simulationXData,dataIndices);
    resolution = constructResolution(resolutionType,resolutionParamIndex,...
        shiftedData,customFiles,resolutionParams,simulationXData,dataIndices);

end