classdef testExamples < matlab.unittest.TestCase

    properties (TestParameter)
        exampleFile = {'orsoDSPCStandardLayers',...
            'DPPCCustomXYScript',...
            'testCppCustomLayers',...
            'DSPCMonolayerStandardLayers',...
            'DSPCMonolayerTwoContrasts',...
            'DSPCMonolayerCustomLayers'};
        exampleName = {'Orso lipid example',...
            'Custom DPPC',...
            'Orso lipid example - custom layers',...
            'DSPC monolayers',...
            'DSPC monolayers',...
            'DSPC custom layers'};
        exampleModel = {'standard layers',...
            'custom xy',...
            'custom layers',...
            'standard layers',...
            'standard layers',...
            'custom layers'}; 
        exampleContrastCount = {3,...
            3,...
            3,...
            4,...
            2,...
            2}; 

    end


    methods (Test,ParameterCombination="sequential")
        % Runs the different examples sequentially 
        function testExample(testCase, exampleFile, exampleName, exampleModel, exampleContrastCount)
                testCase.verifyEqual(exist(exampleFile,'file'), 2);
                run(exampleFile); % runs the example file
                testCase.verifyEqual(problem.experimentName, exampleName);
                testCase.verifyEqual(problem.modelType, exampleModel);
                testCase.verifyEqual(problem.contrasts.numberOfContrasts, exampleContrastCount);
                close all;
        end
    end
end



