Description of parseCells
parseCells
PURPOSE
Splits up the master input list of all arrays into separate arrays
SYNOPSIS
function [repeatLayers,allData,dataLimits,simLimits,contrastLayers,layersDetails,customFiles] = parseCells(problemDefCells)
DESCRIPTION
 Splits up the master input list of all arrays into separate arrays
 The min input array 'problemDefCells' is a master array where
 all the cell arrays are grouped together. There are
 repeatLayers      - controls repeating of the layers stack
 allData           - Array of all the data arrays
 dataLimits        - Min max limits in q for the data arrays
 simLimits         - Limits in Q for the reflkectivity simulations
 Layers details    - Master array of all available layers
 contrastLayers    - Which specific combination of arrays are needed for
                     each contrast.
 Custom files      - Filenames and path for any custom files used
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
domainsTFCustomLayersParallelContrasts Single threaded version of the custom layers, domainsTF reflectivity
domainsTFCustomLayersParallelPoints Single threaded version of the custom layers, domainsTF reflectivity
domainsTFCustomLayersSingle Single threaded version of the custom layers, domainsTF reflectivity
domainsTFCustomXYParallelContrasts Extract individual cell arrays
domainsTFCustomXYParallelPoints Extract individual cell arrays
domainsTFCustomXYSingle Extract individual cell arrays
domainsTFStandardLayersParallelContrasts Single threaded version of the Standard Layers calculation
domainsTFStandardLayersParallelPoints Single threaded version of the Standard Layers calculation
domainsTFStandardLayersSingle Single threaded version of the Standard Layers calculation
standardTFCustomLayersParallelContrasts Multi threaded version of the custom layers, standardTF reflectivity
standardTFCustomLayersParallelPoints Multi threaded version of the custom layers over reflectivity poimnts
standardTFCustomLayersSingle Single threaded version of the custom layers, standardTF reflectivity
standardTFCustomXYParallelContrasts Extract individual cell arrays
standardTFCustomXYParallelPoints Multi threaded version of the custom XY profile over reflectivity points
standardTFCustomXYSingle Extract individual cell arrays
standardTFStandardLayersParallelContrasts Standard Layers calculation paralelised over the outer loop
standardTFStandardLayersParallelPoints Standard Layers calculation paralelised over the inner loop
standardTFStandardLayersSingle Single threaded version of the Standard Layers calculation
SOURCE CODE
function [repeatLayers,allData,dataLimits,simLimits,contrastLayers,layersDetails,customFiles] = parseCells(problemDefCells)
% Splits up the master input list of all arrays into separate arrays
% The min input array 'problemDefCells' is a master array where
% all the cell arrays are grouped together. There are
% repeatLayers      - controls repeating of the layers stack
% allData           - Array of all the data arrays
% dataLimits        - Min max limits in q for the data arrays
% simLimits         - Limits in Q for the reflkectivity simulations
% Layers details    - Master array of all available layers
% contrastLayers    - Which specific combination of arrays are needed for
%                     each contrast.
% Custom files      - Filenames and path for any custom files used
repeatLayers = problemDefCells{1};
allData = problemDefCells{2};
dataLimits = problemDefCells{3};
simLimits = problemDefCells{4};
contrastLayers = problemDefCells{5};
layersDetails = problemDefCells{6};
customFiles = problemDefCells{14};
end