Description of betar
betar
PURPOSE
BETAR Beta random numbers
SYNOPSIS
function r=betar(m,n,a,b)
DESCRIPTION
BETAR  Beta random numbers
 BETAR(m,n,a,b) m,n shape of the result, a,b beta parameters
CROSS-REFERENCE INFORMATION
This function calls:
chir CHIR Chi squared random numbers
chir CHIR Chi squared random numbers
This function is called by:
betabinr BETABINR Beta Binomial random numbers
betabinr BETABINR Beta Binomial random numbers
SOURCE CODE
function r=betar(m,n,a,b)
%BETAR  Beta random numbers
% BETAR(m,n,a,b) m,n shape of the result, a,b beta parameters
% Marko Laine <marko.laine@fmi.fi>
% $Revision: 1.5 $  $Date: 2012/09/27 11:47:33 $
xa = chir(m,n,2*a);
xb = chir(m,n,2*b);
r = xa./(xa+xb);