Description of binpf
binpf
PURPOSE
BINPF Binomial probability function
SYNOPSIS
function y=binpf(x,n,p)
DESCRIPTION
 BINPF Binomial probability function
 BINPF(x,n,p)
CROSS-REFERENCE INFORMATION
This function calls:
binom BINOM(n,k) binomial coefficient
binom BINOM(n,k) binomial coefficient
This function is called by:
bindf BINDF Cumulative Binomial probability
bindf BINDF Cumulative Binomial probability
SOURCE CODE
function y=binpf(x,n,p)
% BINPF Binomial probability function
% BINPF(x,n,p)
% Marko Laine <marko.laine@fmi.fi>
% $Revision: 1.3 $  $Date: 2012/09/27 11:47:33 $
y = binom(n,x).*p.^x.*(1-p).^(n-x);