Description of invchir
invchir
PURPOSE
INVCHIR(m,n,N0,S2) inverse scaled chi squared random numbers
SYNOPSIS
function r=invchir(m,n,N0,S2)
DESCRIPTION
 INVCHIR(m,n,N0,S2) inverse scaled chi squared random numbers
CROSS-REFERENCE INFORMATION
This function calls:
chir CHIR Chi squared random numbers
chir CHIR Chi squared random numbers
This function is called by:
hyperpriorupdate hyperpriorupdate - default hyper prior update function for mcmcrun
invchi1r INVCHI1R(m,n,N0,S2) inverse scaled chi random numbers
hyperpriorupdate hyperpriorupdate - default hyper prior update function for mcmcrun
invchi1r INVCHI1R(m,n,N0,S2) inverse scaled chi random numbers
SOURCE CODE
function r=invchir(m,n,N0,S2)
% INVCHIR(m,n,N0,S2) inverse scaled chi squared random numbers
% Marko Laine <marko.laine@fmi.fi>
% $Revision: 1.4 $  $Date: 2012/09/27 11:47:37 $
r = N0.*S2./chir(m,n,N0);