Description of norpf
norpf
PURPOSE
NORPF(x,mu,sigma2) Normal (Gaussian) density function
SYNOPSIS
function y=norpf(x,mu,sigma2)
DESCRIPTION
 NORPF(x,mu,sigma2)  Normal (Gaussian) density function
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
density DENSITY Density estimator using Gaussian kernel
density2d DENSITY2D 2 dimensinal density estimator
threemodesex %
histp HISTP Histogram scaled as relative frequencies (probabilities)
lognorpf LOGNORPF Lognormal probability density
mcmcplot MCMCPLOT Plot mcmc chain
density DENSITY Density estimator using Gaussian kernel
density2d DENSITY2D 2 dimensinal density estimator
histp HISTP Histogram scaled as relative frequencies (probabilities)
lognorpf LOGNORPF Lognormal probability density
mcmcplot MCMCPLOT Plot mcmc chain
SOURCE CODE
function y=norpf(x,mu,sigma2)
% NORPF(x,mu,sigma2)  Normal (Gaussian) density function
% Marko Laine <marko.laine@fmi.fi>
% $Revision: 1.4 $  $Date: 2012/09/27 11:47:38 $
if nargin < 2, mu=0; end
if nargin < 3, sigma2=1; end
y=1./sqrt(2*pi*sigma2).*exp(-0.5*(x-mu).^2 ./sigma2);