Description of norr
norr
PURPOSE
NORR(m,n,mu,sigma2) Normal (Gaussian) random numbers
SYNOPSIS
function r=norr(m,n,mu,sigma2)
DESCRIPTION
 NORR(m,n,mu,sigma2)  Normal (Gaussian) random numbers
 m,n shape of the result, mu mean, sigma2 variance
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
hyperpriorupdate hyperpriorupdate - default hyper prior update function for mcmcrun
lognorr LOGNORR Random numbers from lognormal distribution
poir POIR random deviates from poisson distribution
tr TR Random numbers from the t distribution
hyperpriorupdate hyperpriorupdate - default hyper prior update function for mcmcrun
lognorr LOGNORR Random numbers from lognormal distribution
poir POIR random deviates from poisson distribution
tr TR Random numbers from the t distribution
SOURCE CODE
function r=norr(m,n,mu,sigma2)
% NORR(m,n,mu,sigma2)  Normal (Gaussian) random numbers
% m,n shape of the result, mu mean, sigma2 variance
% Marko Laine <marko.laine@fmi.fi>
% $Revision: 1.5 $  $Date: 2012/09/27 11:47:38 $
if nargin < 3, mu=0; end
if nargin < 4, sigma2=1; end
r = randn(m,n).*sqrt(sigma2) + mu;