Description of plotBayes
plotBayes
PURPOSE
SYNOPSIS
function plotBayes(problem,results,varargin)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
bayesShadedPlot Plot the shaded reflectivities from Bayes output
plotBayesCorrFig
plotRefSLD Convert the problem class to a struct.
This function is called by:
SOURCE CODE
function plotBayes(problem,results,varargin)
        figure(10); clf; plotRefSLD(problem,results)
        h2 = figure(30); clf; %subplot(1,2,1)
        bayesShadedPlot(problem,results,'fit','average','KeepAxes',true,'interval',95,'q4',false)
        h3 = figure(40); clf
        mcmcplot(results.chain,[],results.fitNames,'hist');
        h4 = figure(5); clf;
        plotBayesCorrFig(results.chain,results.fitNames,h4)
        h6 = figure(60); clf
        mcmcplot(results.chain,[],results.fitNames,'chainpanel');
end