Description of confIntervals
confIntervals
PURPOSE
SYNOPSIS
function paramIntervals = confIntervals(chain, bestPars, predInt)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
iterShortest Now try to work out the shortest 95% confidence interval..
iterShortest
This function is called by:
calcMCMCstatRefErrors Calculates fits and confidence intervals
SOURCE CODE
function paramIntervals = confIntervals(chain, bestPars, predInt)
numberOfParams = size(chain,2);
type = 'iter';
% Work out the numerical shotest prediction intervals.
switch type
    case 'CDF'
        % (1) Use the CDF
        paramIntervals = calcLimits(chain,numberOfParams,bestPars,predInt);
    case 'iter'
        % (2) Use an iterative shortest interval
        paramIntervals = iterShortest(chain,numberOfParams,bestPars,predInt);
end
end