Description of parallelPoints
parallelPoints
PURPOSE
Single threaded version of the Standard Layers calculation
SYNOPSIS
function [outSsubs,backgs,qzshifts,scalefactors,bulkIns,bulkOuts,resols,chis,reflectivity,Simulation,shifted_data,layerSlds,domainSldProfiles,allLayers,allRoughs] = parallelPoints(problemDef,problemDefCells,controls)
DESCRIPTION
 Single threaded version of the Standard Layers calculation
 This is the main reflectivity calculation of the standard layers
 calculation type. It extracts the required parameters for the contrasts
 from the input arrays, then passes the main calculation to
 'standardLayersCore', which carries out the calculation itself.
 The core calculation is common for both standard and custom layers.
CROSS-REFERENCE INFORMATION
This function calls:
parallelPoints Single threaded version of the custom layers, domainsTF reflectivity
parallelPoints Extract individual cell arrays
parallelPoints Single threaded version of the Standard Layers calculation
parallelPoints Multi threaded version of the custom layers over reflectivity poimnts
parallelPoints Multi threaded version of the custom XY profile over reflectivity points
parallelPoints Standard Layers calculation paralelised over the inner loop
backSort Distributes the background and shift values among the different contrasts
chiSquared Chi-squared function is used to evaluate the goodness of fit.
extractProblemParams Extract individual parameters from problemDef
allocateLayersForContrast Decide which layers are needed for a particular contrast.
allocateParamsToLayers Allocates parameters from the parameter array to the correct layers
parseCells Splits up the master input list of all arrays into separate arrays
This function is called by:
parallelContrasts Single threaded version of the custom layers, domainsTF reflectivity
parallelPoints Single threaded version of the custom layers, domainsTF reflectivity
single Single threaded version of the custom layers, domainsTF reflectivity
parallelContrasts Single threaded version of the Standard Layers calculation
parallelPoints Single threaded version of the Standard Layers calculation
single Single threaded version of the Standard Layers calculation
parallelContrasts Multi threaded version of the custom layers, nonPolarisedTF reflectivity
parallelPoints Multi threaded version of the custom layers over reflectivity poimnts
single Single threaded version of the custom layers, nonPolarisedTF reflectivity
parallelContrasts Standard Layers calculation paralelised over the outer loop
parallelPoints Standard Layers calculation paralelised over the inner loop
single Single threaded version of the Standard Layers calculation
coreLayersCalculation This is the main reflectivity calculation for all Layers models in the
SOURCE CODE
function [outSsubs,backgs,qzshifts,scalefactors,bulkIns,bulkOuts,resols,chis,reflectivity,...
    Simulation,shifted_data,layerSlds,domainSldProfiles,allLayers,...
    allRoughs] = parallelPoints(problemDef,problemDefCells,controls)
% Single threaded version of the Standard Layers calculation
% This is the main reflectivity calculation of the standard layers
% calculation type. It extracts the required parameters for the contrasts
% from the input arrays, then passes the main calculation to
% 'standardLayersCore', which carries out the calculation itself.
% The core calculation is common for both standard and custom layers.
% Extract individual cell arrays
[repeatLayers,...
 allData,...
 dataLimits,...
 simLimits,~,...
 layersDetails,~] = parseCells(problemDefCells);
% Additionally extract the additional domain layers details
domainContrastLayers = problemDefCells{19};
% Extract individual parameters from problemDef struct
[numberOfContrasts, geometry, contrastBackgrounds, contrastQzshifts, contrastScalefactors, contrastBulkIns, contrastBulkOuts,...
contrastResolutions, backs, shifts, scalefactor, bulkIn, bulkOut, res, dataPresent, nParams, params,...
~, resample, backsType, ~] =  extractProblemParams(problemDef);
calcSld = controls.calcSldDuringFit;
useImaginary = problemDef.useImaginary;
allDomainRatios = problemDef.domainRatio;
contrastDomainRatios = problemDef.contrastDomainRatios;
domainRatio = 1;    % Default for compile.
% Allocate the memory for the output arrays before the main loop
backgs = zeros(numberOfContrasts,1);
qzshifts = zeros(numberOfContrasts,1);
scalefactors = zeros(numberOfContrasts,1);
bulkIns = zeros(numberOfContrasts,1);
bulkOuts = zeros(numberOfContrasts,1);
resols = zeros(numberOfContrasts,1);
allRoughs = zeros(numberOfContrasts,1);
outSsubs = zeros(numberOfContrasts,1);
chis =  zeros(numberOfContrasts,1);
layerSlds = cell(numberOfContrasts,2);
domainSldProfiles = cell(numberOfContrasts,2);
shifted_data = cell(numberOfContrasts,1);
reflectivity = cell(numberOfContrasts,1);
for i = 1:numberOfContrasts
    reflectivity{i} = [1 1 ; 1 1];
end
Simulation = cell(numberOfContrasts,1);
for i = 1:numberOfContrasts
    Simulation{i} = [1 1 ; 1 1];
end
allLayers = cell(numberOfContrasts,2);
for i = 1:numberOfContrasts
    allLayers{i,1} = [1 1 1; 1 1 1];
    allLayers{i,2} = [1 1 1; 1 1 1];
end
tempSldProfiles = cell(numberOfContrasts,1);
for i = 1:numberOfContrasts
    tempSldProfiles{i} = {[1 1 ; 1 1],[1 1 ; 1 1]};
end
calcAllLayers = cell(numberOfContrasts,2);
for i = 1:numberOfContrasts
    calcAllLayers{i,1} = [1 ; 1];
    calcAllLayers{i,2} = [1 ; 1];
end
tempAllLayers = cell(numberOfContrasts,1);
for i = 1:numberOfContrasts
    tempAllLayers{i} = {[1 1 1;1 1 1],[1 1 1;1 1 1]};
end
tempLayerSlds = cell(numberOfContrasts,1);
for i = 1:numberOfContrasts
    tempLayerSlds{i} = {[1 1 1;1 1 1],[1 1 1;1 1 1]};
end
% end memory allocation.
% First we need to allocate the absolute values of the input
% parameters to all the layers in the layers list. This only needs
% to be done once, and so is done outside the contrasts loop
outParameterisedLayers = allocateParamsToLayers(params, layersDetails);
% Resample params if requiired
resamPars = controls.resamPars;
% Loop over all the contrasts
for i = 1:numberOfContrasts
    % Get the domain ratio for this contrast
    thisContrastDR = contrastDomainRatios(i);
    if isempty(thisContrastDR)
        thisContrastDR = 1;
    end
    domainRatio = allDomainRatios(thisContrastDR);
    % Extract the relevant parameter values for this contrast
    % from the input arrays.
    % First need to decide which values of the backgrounds, scalefactors
    % data shifts and bulk contrasts are associated with this contrast
    [thisBackground,thisQzshift,thisScalefactor,thisBulkIn,thisBulkOut,thisResol] = backSort(contrastBackgrounds(i),contrastQzshifts(i),contrastScalefactors(i),contrastBulkIns(i),contrastBulkOuts(i),contrastResolutions(i),backs,shifts,scalefactor,bulkIn,bulkOut,res);
    % Also need to determine which layers from the overall layers list
    % are required for this contrast, and put them in the correct order
    % according to geometry. We run it twice, once for each domain...
    thisContrastLayers1 = allocateLayersForContrast(domainContrastLayers{1},outParameterisedLayers,useImaginary);
    thisContrastLayers2 = allocateLayersForContrast(domainContrastLayers{2},outParameterisedLayers,useImaginary);
    % For the other parameters, we extract the correct ones from the input
    % arrays
    thisRough = params(1);      % Substrate roughness is always first parameter for standard layers
    thisRepeatLayers = repeatLayers{i};
    thisResample = resample(i);
    thisData = allData{i};
    thisDataPresent = dataPresent(i);
    thisDataLimits = dataLimits{i};
    thisSimLimits = simLimits{i};
    thisBacksType = backsType(i);
    % Now call the core layers reflectivity calculation
    % In this case we are single cored, so we do not parallelise over
    % points
    parallelPoints = 'points';
    % Call the core layers calculation - need to do this once for each
    % domain
    [sldProfile1,reflect1,Simul1,shifted_dat,layerSld1,resamLayers1,~,thisSsubs]= nonPolarisedTF.coreLayersCalculation(thisContrastLayers1, thisRough, ...
    geometry, thisBulkIn, thisBulkOut, thisResample, calcSld, thisScalefactor, thisQzshift,...
    thisDataPresent, thisData, thisDataLimits, thisSimLimits, thisRepeatLayers,...
    thisBackground,thisResol,thisBacksType,nParams,parallelPoints,resamPars,useImaginary);
    [sldProfile2,reflect2,Simul2,~,layerSld2,resamLayers2,~,~] = nonPolarisedTF.coreLayersCalculation(thisContrastLayers2, thisRough, ...
    geometry, thisBulkIn, thisBulkOut, thisResample, calcSld, thisScalefactor, thisQzshift,...
    thisDataPresent, thisData, thisDataLimits, thisSimLimits, thisRepeatLayers,...
    thisBackground,thisResol,thisBacksType,nParams,parallelPoints,resamPars,useImaginary);
    % Calculate the average reflectivities....
    [totReflect,totSimul] = domainsTF.averageReflectivity(reflect1,reflect2,Simul1,Simul2,domainRatio);
    % Get an overall chi-squared for the new averaged curve..
    thisChiSquared = chiSquared(shifted_dat,totReflect,length(params));
    % Store returned values for this contrast in the output arrays.
    % As well as the calculated profiles, we also store a record of
    % the other values (background, scalefactors etc) for each contrast
    % for future use.
    outSsubs(i) = thisSsubs;
    tempSldProfiles{i} = {sldProfile1, sldProfile2};
    reflectivity{i} = totReflect;
    Simulation{i} = totSimul;
    shifted_data{i} = shifted_dat;
    tempLayerSlds{i} = {layerSld1, layerSld2};
    tempAllLayers{i} = {resamLayers1, resamLayers2};
    chis(i) = thisChiSquared;
    backgs(i) = thisBackground;
    qzshifts(i) = thisQzshift;
    scalefactors(i) = thisScalefactor;
    bulkIns(i) = thisBulkIn;
    bulkOuts(i) = thisBulkOut;
    resols(i) = thisResol;
    allRoughs(i) = thisRough;
end
for i = 1:numberOfContrasts
    theseDomainSLDs = tempSldProfiles{i};
    domainSldProfiles{i,1} = theseDomainSLDs{1};
    domainSldProfiles{i,2} = theseDomainSLDs{2};
    theseAllLayers = tempAllLayers{i};
    allLayers{i,1} = theseAllLayers{1};
    allLayers{i,2} = theseAllLayers{2};
    theseLayerSlds = tempLayerSlds{i};
    layerSlds{i,1} = theseLayerSlds{1};
    layerSlds{i,2} = theseLayerSlds{2};
end
end