

problem.contrasts.contrasts{1}

debug_json_struct.contrasts

% Get fieldnames (and order) from the json...
jsonFields = fieldnames(debug_json_struct.contrasts);

% get one of the matlab structs
mStruct = problem.contrasts.contrasts{1};

% remove the repeats field...
mStruct = rmfield(mStruct,'repeatLayers');

% rename the fields...
newFeildNames = ["background",...
                "background_action",...
                "bulk_in"          ,...
                "bulk_out"         ,...
                "data"            ,...
                "model"           ,...
                "name"            ,...
                "resample"        ,...
                "resolution"      ,...
                "scalefactor"     ];

mStruct = cell2struct(struct2cell(mStruct), newFieldNames);

% Order them according to the json requirements...
mStruct = orderfields(mStruct,jsonFields);