Description of benchMain
benchMain
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
legacyChanges
reflectivity_calculation Preallocatin of outputs
reflectivity_calculation Preallocatin of outputs
reflectivity_calculation global RAT_DEBUG DEBUGVARS
legacyChanges
legacyChanges
legacyChanges
legacyChanges
legacyChanges
legacyChanges
legacyChanges
legacyChanges
legacyChanges
legacyChanges
reflectivity_calculation
reflectivity_calculation
reflectivity_calculation
This function is called by:
SOURCE CODE
addpath('/home/arwel/Documents/RascalDev/RAT'); %linux
addRatPaths
%a = load('standardLayersProblem.mat');     %Standard Layers Example
a = load('L1 DTSp ANTA hBamAB dCDE POPC +- hSurA.mat');
problem = a.problem;
problem = legacyChanges(problem);
%initial calculation
tic
problem = reflectivity_calculation(problem);
toc
figure(3); clf; hold on
for i = 1:16
    problem = a.problem;
    problem.numberOfContrasts = i;
    problem = legacyChanges(problem);
    tic
    problem = reflectivity_calculation(problem);
    t(i) = toc;
    plot(i,t(i),'bo');
end
figure(1); clf; hold on;
for i = 1:problem.numberOfContrasts
    thisData = problem.shifted_data{i};
    mult = 10^(2*i);
    thisData(:,2) = thisData(:,2) / mult;
    thisData(:,3) = thisData(:,3) / mult;
    errorbar(thisData(:,1),thisData(:,2),thisData(:,3),'o');
    thisFit = problem.calculations.Simulation{i};
    thisFit(:,2) = thisFit(:,2) / mult;
    plot(thisFit(:,1),thisFit(:,2));
end
set(gca,'YScale','log','XScale','log','xlim',[0.05 0.4]);
%
%
% figure(2); clf; hold on
% for i = 1:problem.numberOfContrasts
%     thisSld = problem.calculations.slds{i};
%     plot(thisSld(:,1),thisSld(:,2));
% end
%rmRatPaths