Description of makeAllMexes
makeAllMexes
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
backSort_makeMex UNTITLED Generate static library backSort from backSort.
backSort_makeMex UNTITLED Generate static library backSort from backSort.
callReflectivity_makeMex UNTITLED Generate static library callReflectivity from callReflectivity.
callReflectivity_makeMex UNTITLED Generate static library callReflectivity from callReflectivity.
chiSquared_makeMex UNTITLED Generate static library chiSquared from chiSquared.
chiSquared_makeMex UNTITLED Generate static library chiSquared from chiSquared.
groupLayers_Mod_makeMex UNTITLED Generate static library groupLayers_Mod from groupLayers_Mod.
groupLayers_Mod_makeMex UNTITLED Generate static library groupLayers_Mod from groupLayers_Mod.
makeSLDProfiles_makeMex UNTITLED Generate static library makeSLDProfiles from makeSLDProfiles.
makeSLDProfiles_makeMex UNTITLED Generate static library makeSLDProfiles from makeSLDProfiles.
shiftdata_makeMex UNTITLED Generate static library shiftdata from shiftdata.
shiftdata_makeMex UNTITLED Generate static library shiftdata from shiftdata.
standard_layers_mod_makeMex UNTITLED Generate static library standard_layers_mod from
standard_layers_mod_makeMex UNTITLED Generate static library standard_layers_mod from
This function is called by:
SOURCE CODE
path = '/Users/arwelhughes/coding/RAT/';
addpath(path)
addRatPaths;
disp('Mexing backSort');
backSort_makeMex;
disp('Mexing callReflectivity');
callReflectivity_makeMex;
disp('Mexing chiSquared');
chiSquared_makeMex;
disp('Mexing groupLayers');
groupLayers_Mod_makeMex;
disp('Mexing makeSLDProfiles');
makeSLDProfiles_makeMex;
disp('Mexing resampleLayers');
resampleLayers_makeMex;
disp('Mexing shiftData');
shiftdata_makeMex;
disp('Mexing standard_layers_mod');
standard_layers_mod_makeMex;
% disp('Mexing unpackparams');
% unpackPars_makeMex;