function [qzshifts,scalefactors,bulkIns,bulkOuts,chis,reflectivity,...
    simulation,shiftedData,backgrounds,resolutions,domainSldProfiles,...
    domainLayers,domainResampledLayers,subRoughs] = standardLayers(problemStruct,controls)
    % This is the main reflectivity calculation of the standard layers
    % calculation type. It extracts the required parameters for the contrasts
    % from the input arrays, then passes the main calculation to
    % 'coreLayersCalculation', which carries out the calculation itself. 
    % The core calculation is common for both standard and custom layers.
    
    % Extract parameters from problemStruct
    [numberOfContrasts, geometry, contrastBackgroundIndices, contrastQzshiftIndices,...
     contrastScalefactorIndices, contrastBulkInIndices, contrastBulkOutIndices,...
     contrastResolutionIndices, contrastDomainRatioIndices, backgroundParamValues,...
     qzshiftValues, scalefactorValues, bulkInValues, bulkOutValues,...
     resolutionParamValues, domainRatioValues, dataPresent, nParams, paramValues,...
     resample, contrastBackgroundTypes, contrastBackgroundActions,...
     contrastResolutionTypes, contrastCustomFiles, useImaginary,...
     repeatLayers, data, dataLimits, simulationLimits, inputContrastLayers,...
     layersDetails, customFiles, domainContrastLayers...
     ] = extractProblemParams(problemStruct);
    
    calcSld = controls.calcSldDuringFit;
    parallel = controls.parallel;
    numSimulationPoints = controls.numSimulationPoints;
    resampleMinAngle = controls.resampleMinAngle;
    resampleNPoints = controls.resampleNPoints;
    
    % Allocate the memory for the output arrays before the main loop
    domainRatios = zeros(numberOfContrasts,1);
    subRoughs = zeros(numberOfContrasts,1);
    chis = zeros(numberOfContrasts,1);
    
    reflectivity = cell(numberOfContrasts,1);   
    simulation = cell(numberOfContrasts,1);
    shiftedData = cell(numberOfContrasts,1);
    backgrounds = cell(numberOfContrasts,1);
    resolutions = cell(numberOfContrasts,1);
    domainSldProfiles = cell(numberOfContrasts,2);
    domainLayers = cell(numberOfContrasts,2);
    domainResampledLayers = cell(numberOfContrasts,2);

    sldProfiles = cell(numberOfContrasts,1);    
    layers = cell(numberOfContrasts,1);
    resampledLayers = cell(numberOfContrasts,1);    
    
    contrastLayers1 = cell(numberOfContrasts,1);   
    contrastLayers2 = cell(numberOfContrasts,1);
    slds1 = cell(numberOfContrasts,1);   
    slds2 = cell(numberOfContrasts,1);

    for i = 1:numberOfContrasts
        contrastLayers1{i} = zeros(1,6);
        contrastLayers2{i} = zeros(1,6);

        slds1{i} = zeros(1,3);
        slds2{i} = zeros(1,3);

        domainLayers{i,1} = zeros(1,6);
        domainLayers{i,2} = zeros(1,6);
        domainResampledLayers{i,1} = zeros(1,6);
        domainResampledLayers{i,2} = zeros(1,6);
    end

    % Extract the relevant parameter values for this contrast from the
    % input arrays. We need to determine which values of the data shifts,
    % scalefactors, and bulk contrasts are associated with this contrast.
    [qzshifts,scalefactors,bulkIns,bulkOuts] = backSort(...
     contrastQzshiftIndices,contrastScalefactorIndices,...
     contrastBulkInIndices,contrastBulkOutIndices,...
     qzshiftValues,scalefactorValues,bulkInValues,bulkOutValues);

    for i = 1:numberOfContrasts

        % Get the domain ratio for this contrast
        if isempty(contrastDomainRatioIndices(i))
            contrastDomainRatioIndices(i) = 1;
        end
        domainRatios(i) = domainRatioValues(contrastDomainRatioIndices(i));

    end


    switch lower(problemStruct.modelType)
        
        case coderEnums.modelTypes.StandardLayers

            % First we need to allocate the absolute values of the input
            % parameters to all the layers in the layers list. This only needs
            % to be done once, and so is done outside the contrasts loop
            layerValues = allocateParamsToLayers(paramValues, layersDetails);

            for i = 1:numberOfContrasts

                % Substrate roughness is always first parameter for standard layers
                subRoughs(i) = paramValues(1);
    
                % Also need to determine which layers from the overall layers list
                % are required for this contrast, and put them in the correct order 
                % according to geometry. We run it twice, once for each domain
                contrastLayers1{i} = allocateLayersForContrast(domainContrastLayers{inputContrastLayers{i}(1)},layerValues);
                contrastLayers2{i} = allocateLayersForContrast(domainContrastLayers{inputContrastLayers{i}(2)},layerValues);

            end

        case coderEnums.modelTypes.CustomLayers

            numberOfOutputColumns = 6;
            [contrastLayers,subRoughs] = domainsTF.processCustomFunction( ...
             contrastBulkInIndices,contrastBulkOutIndices,bulkInValues,bulkOutValues, ...
             contrastCustomFiles,numberOfContrasts,numberOfOutputColumns,customFiles,paramValues,useImaginary);

            for i = 1:size(contrastLayers,1)
                contrastLayers1{i} = contrastLayers{i,1};
                contrastLayers2{i} = contrastLayers{i,2};
            end

        case coderEnums.modelTypes.CustomXY

            numberOfOutputColumns = 3;
            [slds,subRoughs] = domainsTF.processCustomFunction(contrastBulkInIndices,contrastBulkOutIndices,...
            bulkInValues,bulkOutValues,contrastCustomFiles,numberOfContrasts,numberOfOutputColumns,customFiles,paramValues,useImaginary);
    
            for i = 1:size(slds,1)
                slds1{i} = slds{i,1};
                slds2{i} = slds{i,2};
            end

       otherwise
            
            coderException(coderEnums.errorCodes.invalidOption, 'The model type "%s" is not supported', problemStruct.modelType);

    end

    if strcmpi(problemStruct.modelType, coderEnums.modelTypes.CustomXY)

        if strcmpi(parallel, coderEnums.parallelOptions.Contrasts)
        
            parfor i = 1:numberOfContrasts

                [inputBackground,inputResolution,inputShiftedData,...
                 simulationXData,dataIndices...
                 ] = setupCoreReflectivityCalculation(...
                 contrastBackgroundIndices{i},contrastResolutionIndices{i},...
                 backgroundParamValues,resolutionParamValues,qzshifts(i),...
                 scalefactors(i),dataPresent(i),data{i},dataLimits{i},...
                 simulationLimits{i},contrastBackgroundTypes{i},...
                 contrastResolutionTypes{i},customFiles,numSimulationPoints);
        
                [chis(i),...
                 reflectivity{i},simulation{i},shiftedData{i},backgrounds{i},...
                 resolutions{i},sldProfiles{i},layers{i},resampledLayers{i}...
                 ] = contrastCustomXYCalculation(bulkIns(i),bulkOuts(i),domainRatios(i),...
                 inputShiftedData,...
                 simulationXData,dataIndices,...
                 inputResolution,inputBackground,...
                 contrastBackgroundActions{i},...
                 nParams,parallel,...
                 resampleMinAngle,resampleNPoints,...
                 subRoughs(i),slds1{i},slds2{i});
    
            end
        
        else
            
            for i = 1:numberOfContrasts

                [inputBackground,inputResolution,inputShiftedData,...
                 simulationXData,dataIndices...
                 ] = setupCoreReflectivityCalculation(...
                 contrastBackgroundIndices{i},contrastResolutionIndices{i},...
                 backgroundParamValues,resolutionParamValues,qzshifts(i),...
                 scalefactors(i),dataPresent(i),data{i},dataLimits{i},...
                 simulationLimits{i},contrastBackgroundTypes{i},...
                 contrastResolutionTypes{i},customFiles,numSimulationPoints);
                
                [chis(i),...
                 reflectivity{i},simulation{i},shiftedData{i},backgrounds{i},...
                 resolutions{i},sldProfiles{i},layers{i},resampledLayers{i}...
                 ] = contrastCustomXYCalculation(bulkIns(i),bulkOuts(i),domainRatios(i),...
                 inputShiftedData,...
                 simulationXData,dataIndices,...
                 inputResolution,inputBackground,...
                 contrastBackgroundActions{i},...
                 nParams,parallel,...
                 resampleMinAngle,resampleNPoints,...
                 subRoughs(i),slds1{i},slds2{i});
    
            end
        
        end

    else

        if strcmpi(parallel, coderEnums.parallelOptions.Contrasts)
        
            % Loop over all the contrasts
            parfor i = 1:numberOfContrasts
    
                [inputBackground,inputResolution,inputShiftedData,...
                 simulationXData,dataIndices...
                 ] = setupCoreReflectivityCalculation(...
                 contrastBackgroundIndices{i},contrastResolutionIndices{i},...
                 backgroundParamValues,resolutionParamValues,qzshifts(i),...
                 scalefactors(i),dataPresent(i),data{i},dataLimits{i},...
                 simulationLimits{i},contrastBackgroundTypes{i},...
                 contrastResolutionTypes{i},customFiles,numSimulationPoints);
            
                [chis(i),...
                 reflectivity{i},simulation{i},shiftedData{i},sldProfiles{i},...
                 layers{i},resampledLayers{i}...
                 ] = contrastLayersCalculation(bulkIns(i),bulkOuts(i),domainRatios(i),...
                 inputShiftedData,...
                 simulationXData,dataIndices,...
                 inputResolution,inputBackground,...
             repeatLayers(i),...
                 contrastBackgroundActions{i},...
                 nParams,parallel,...
                 resampleMinAngle,resampleNPoints,resample(i),...
                 geometry,subRoughs(i),calcSld,contrastLayers1{i},contrastLayers2{i});
    
                backgrounds{i} = inputBackground;
                resolutions{i} = inputResolution;
        
            end
        
        else
        
            % Loop over all the contrasts
            for i = 1:numberOfContrasts
    
                [inputBackground,inputResolution,inputShiftedData,...
                 simulationXData,dataIndices...
                 ] = setupCoreReflectivityCalculation(...
                 contrastBackgroundIndices{i},contrastResolutionIndices{i},...
                 backgroundParamValues,resolutionParamValues,qzshifts(i),...
                 scalefactors(i),dataPresent(i),data{i},dataLimits{i},...
                 simulationLimits{i},contrastBackgroundTypes{i},...
                 contrastResolutionTypes{i},customFiles,numSimulationPoints);
    
                [chis(i),...
                 reflectivity{i},simulation{i},shiftedData{i},sldProfiles{i},...
                 layers{i},resampledLayers{i}...
                 ] = contrastLayersCalculation(bulkIns(i),bulkOuts(i),domainRatios(i),...
                 inputShiftedData,...
                 simulationXData,dataIndices,...
                 inputResolution,inputBackground,...
                 repeatLayers(i),...
                 contrastBackgroundActions{i},...
                 nParams,parallel,...
                 resampleMinAngle,resampleNPoints,resample(i),...
                 geometry,subRoughs(i),calcSld,contrastLayers1{i},contrastLayers2{i});
    
                backgrounds{i} = inputBackground;
                resolutions{i} = inputResolution;
    
            end
        
        end

    end
    
    for i = 1:numberOfContrasts
    
        contrastSldProfiles = sldProfiles{i};
        domainSldProfiles{i,1} = contrastSldProfiles{1};
        domainSldProfiles{i,2} = contrastSldProfiles{2};
    
        contrastLayerValues = layers{i};
        domainLayers{i,1} = contrastLayerValues{1};
        domainLayers{i,2} = contrastLayerValues{2};
    
        contrastResampledLayers = resampledLayers{i};
        domainResampledLayers{i,1} = contrastResampledLayers{1};
        domainResampledLayers{i,2} = contrastResampledLayers{2};
    
    end

    % Remove dummy imaginary column if present
    if ~useImaginary
        for i=1:numberOfContrasts
            domainLayers{i,1}(:,3) = [];
            domainLayers{i,2}(:,3) = [];
            domainResampledLayers{i,1}(:,3) = [];
            domainResampledLayers{i,2}(:,3) = [];
        end
    end

end


function [chi,reflectivity,simulation,...
    shiftedData,sldProfile,layers,...
    resampledLayers] = contrastLayersCalculation(bulkIn,bulkOut,domainRatio,...
    shiftedData,...
    simulationXData,dataIndices,...
    resolution,background, ...
    repeatLayers,...
    backgroundAction,nParams,...
    parallel,resampleMinAngle,resampleNPoints,resample,...
    geometry,roughness,calcSld,contrastLayers1,contrastLayers2)
          
    % Call the core layers calculation - need to do this once for each
    % domain
    [reflectivity1,simulation1,~,sldProfile1,layers1,resampledLayers1] = normalTF.coreLayersCalculation( ...
        contrastLayers1,roughness,geometry,bulkIn,bulkOut,resample,calcSld,shiftedData, ...
        simulationXData,dataIndices,repeatLayers,resolution,background, ...
        backgroundAction,parallel,resampleMinAngle,resampleNPoints);

    [reflectivity2,simulation2,shiftedData,sldProfile2,layers2,resampledLayers2] = normalTF.coreLayersCalculation( ...
        contrastLayers2,roughness,geometry,bulkIn,bulkOut,resample,calcSld,shiftedData, ...
        simulationXData,dataIndices,repeatLayers,resolution,background, ...
        backgroundAction,parallel,resampleMinAngle,resampleNPoints);
    
    % Calculate the average reflectivities
    [reflectivity,simulation] = domainsTF.averageReflectivity(reflectivity1,reflectivity2,simulation1,simulation2,domainRatio);

    % Get an overall chi-squared for the new averaged curve
    chi = chiSquared(shiftedData,reflectivity,nParams);

    % Store returned values for this contrast in the output arrays
    sldProfile = {sldProfile1, sldProfile2};
    layers = {layers1, layers2};
    resampledLayers = {resampledLayers1, resampledLayers2};

end

function [chi,reflectivity,simulation,...
    shiftedData,background,resolution,sldProfile,layers,...
    resampledLayers] = contrastCustomXYCalculation(bulkIn,bulkOut,domainRatio,...
    shiftedData,...
    simulationXData,dataIndices,...
    resolution,background, ...
    backgroundAction,nParams,...
    parallel,resampleMinAngle,resampleNPoints,roughness,...
    sld1,sld2)
     
    % Resample the sld profiles
    sldProfile1 = sld1(:,[1,2]);
    sldProfileIm1 = sld1(:,[1,3]);

    sldProfile2 = sld2(:,[1,2]);
    sldProfileIm2 = sld2(:,[1,3]);

    layers1 = resampleLayers(sldProfile1,sldProfileIm1,resampleMinAngle,resampleNPoints);
    layers2 = resampleLayers(sldProfile2,sldProfileIm2,resampleMinAngle,resampleNPoints);

    reflectivityType = 'standardAbeles';
    [reflectivity1,simulation1] = callReflectivity(bulkIn,bulkOut,simulationXData, ...
        dataIndices,1,layers1,roughness,resolution,parallel,reflectivityType);
    [reflectivity2,simulation2] = callReflectivity(bulkIn,bulkOut,simulationXData, ...
        dataIndices,1,layers2,roughness,resolution,parallel,reflectivityType);

    [reflectivity1,simulation1,~] = applyBackgroundCorrection(reflectivity1,simulation1,shiftedData,background,backgroundAction);
    [reflectivity2,simulation2,shiftedData] = applyBackgroundCorrection(reflectivity2,simulation2,shiftedData,background,backgroundAction);

     % Calculate the average reflectivities
    [reflectivity,simulation] = domainsTF.averageReflectivity(reflectivity1,reflectivity2,simulation1,simulation2,domainRatio);

    chi = chiSquared(shiftedData,reflectivity,nParams);

    sldProfile = {sldProfile1, sldProfile2};
    layers = {layers1, layers2};
    resampledLayers = {layers1, layers2};

end
