Description of allocateParamsToLayers
allocateParamsToLayers
PURPOSE
This function takes the list of all layers (in terms of parameter
SYNOPSIS
function outLayers = allocateParamsToLayers(params, layersDetails);
DESCRIPTION
This function takes the list of all layers (in terms of parameter
numbers) in layersDetails, and loops through putting in the correct
parameter value from the parameter array in each layer.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
standardTF_stanlay_parallel global RAT_DEBUG DEBUGVARS
standardTF_stanlay_paraPoints Allocate the memory for the output arrays before the main loop
standardTF_stanlay_paraPoints Allocate the memory for the output arrays before the main loop
standardTF_stanlay_paraContrasts Allocate the memory for the output arrays before the main loop
standardTF_stanlay_paraContrasts Allocate the memory for the output arrays before the main loop
standardTF_stanlay_paraContrasts Allocate the memory for the output arrays before the main loop
standardTF_stanlay_paraPoints Allocate the memory for the output arrays before the main loop
standardTF_stanlay_paraPoints Allocate the memory for the output arrays before the main loop
standardTF_stanlay_paraPoints Allocate the memory for the output arrays before the main loop
standardTF_stanlay_single Allocate the memory for the output arrays before the main loop
standardTF_stanlay_single Allocate the memory for the output arrays before the main loop
standardTF_stanlay_single Allocate the memory for the output arrays before the main loop
SOURCE CODE
function outLayers = allocateParamsToLayers(params, layersDetails);
%This function takes the list of all layers (in terms of parameter
%numbers) in layersDetails, and loops through putting in the correct
%parameter value from the parameter array in each layer.
numberOfLayers = length(layersDetails);
thisOutLayer = zeros(1,5);
outLayers = cell(1,numberOfLayers);
for i = 1:numberOfLayers
    thisLayer = layersDetails{i};
    for n = 1:(length(thisLayer)-1)
        thisVal = thisLayer(n);
        if ~isnan(thisVal)
            thisOutLayer(n) = params(thisVal);
        else
            thisOutLayer(n) = NaN;
        end
    end
    thisOutLayer(length(thisLayer)) = thisLayer(end);
    outLayers{i} = thisOutLayer;
end
end