Description of standardTFCustomLayersReflectivityCalculation
standardTFCustomLayersReflectivityCalculation
PURPOSE
Custom layers reflectivity calculation for standardTF
SYNOPSIS
function [problem,reflectivity,Simulation,shifted_data,layerSlds,sldProfiles,allLayers] = standardTFCustomLayersReflectivityCalculation(problemDef,problemDefCells,problemDefLimits,controls)
DESCRIPTION
 Custom layers reflectivity calculation for standardTF
CROSS-REFERENCE INFORMATION
This function calls:
standardTFCustomLayersParallelContrasts Multi threaded version of the custom layers, standardTF reflectivity
standardTFCustomLayersParallelPoints Multi threaded version of the custom layers over reflectivity poimnts
standardTFCustomLayersSingle Single threaded version of the custom layers, standardTF reflectivity
This function is called by:
standardTFReflectivityCalculation Main function for the standardTF reflectivity calculation
SOURCE CODE
function [problem,reflectivity,Simulation,shifted_data,layerSlds,sldProfiles,allLayers] = standardTFCustomLayersReflectivityCalculation(problemDef,problemDefCells,problemDefLimits,controls)
% Custom layers reflectivity calculation for standardTF
% This function decides on parallelisation options before calling the
% relevant version of the main custom layers calculation. It is more
% efficient to have multiple versions of the core calculation, each dealing
% with a different scheme for parallelisation. These are:
% single    - single threaded teflectivity calculation
% points    - parallelise over points in the reflectivity calculation
% contrasts - parallelise over contrasts.
% Pre-allocation - It's necessary to
% pre-allocate the memory for all the arrays
% for compilation, so do this in this block.
numberOfContrasts = problemDef.numberOfContrasts;
outSsubs = zeros(numberOfContrasts,1);
backgs = zeros(numberOfContrasts,1);
qshifts = zeros(numberOfContrasts,1);
sfs = zeros(numberOfContrasts,1);
nbas = zeros(numberOfContrasts,1);
nbss = zeros(numberOfContrasts,1);
chis = zeros(numberOfContrasts,1);
resols = zeros(numberOfContrasts,1);
allRoughs = zeros(numberOfContrasts,1);
reflectivity = cell(numberOfContrasts,1);
for i = 1:numberOfContrasts
    reflectivity{i} = [1 1 ; 1 1];
end
Simulation = cell(numberOfContrasts,1);
for i = 1:numberOfContrasts
    Simulation{i} = [1 1 ; 1 1];
end
shifted_data = cell(numberOfContrasts,1);
for i = 1:numberOfContrasts
    shifted_data{i} = [1 1 1; 1 1 1];
end
layerSlds = cell(numberOfContrasts,1);
for i = 1:numberOfContrasts
    layerSlds{i} = [1 1 1; 1 1 1];
end
sldProfiles = cell(numberOfContrasts,1);
for i = 1:numberOfContrasts
    sldProfiles{i} = [1 1; 1 1];
end
allLayers = cell(numberOfContrasts,1);
for i = 1:numberOfContrasts
    allLayers{i} = [1 1 1; 1 1 1];
end
% End pre-allocation
para = controls.para;
switch para
    case 'single'
          [outSsubs,backgs,qshifts,sfs,nbas,nbss,resols,chis,reflectivity,...
             Simulation,shifted_data,layerSlds,sldProfiles,allLayers,...
             allRoughs] = standardTFCustomLayersSingle(problemDef,problemDefCells,...
             problemDefLimits,controls);
    case 'points'
          [outSsubs,backgs,qshifts,sfs,nbas,nbss,resols,chis,reflectivity,...
             Simulation,shifted_data,layerSlds,sldProfiles,allLayers,...
             allRoughs] = standardTFCustomLayersParallelPoints(problemDef,problemDefCells,...
             problemDefLimits,controls);
    case 'contrasts'
          [outSsubs,backgs,qshifts,sfs,nbas,nbss,resols,chis,reflectivity,...
             Simulation,shifted_data,layerSlds,sldProfiles,allLayers,...
             allRoughs] = standardTFCustomLayersParallelContrasts(problemDef,problemDefCells,...
             problemDefLimits,controls);
end
problem.ssubs = outSsubs;
problem.backgrounds = backgs;
problem.qshifts = qshifts;
problem.scalefactors = sfs;
problem.nbairs = nbas;
problem.nbsubs = nbss;
problem.resolutions = resols;
problem.calculations.all_chis = chis;
problem.calculations.sum_chi = sum(chis);
problem.allSubRough = allRoughs;
problem.resample = problemDef.resample;
end