Description of standardTF_reflectivityCalculation
standardTF_reflectivityCalculation
PURPOSE
Decide what kind of calculation it is and call the appropriate one
SYNOPSIS
function [problem,reflectivity,Simulation,shifted_data,layerSlds,sldProfiles,allLayers] = standardTF_reflectivityCalculation(problemDef,problemDef_cells,problemDef_limits,controls)
DESCRIPTION
Decide what kind of calculation it is and call the appropriate one
CROSS-REFERENCE INFORMATION
This function calls:
problemDef
standardTF_custLay_reflectivityCalculation Pre-allocation - It's necessary to
standardTF_stanLay_reflectivityCalculation Pre-allocation - It's necessary to
This function is called by:
SOURCE CODE
function [problem,reflectivity,Simulation,shifted_data,layerSlds,sldProfiles,allLayers] = standardTF_reflectivityCalculation(problemDef,problemDef_cells,problemDef_limits,controls)
%Decide what kind of calculation it is and call the appropriate one
type = problemDef.modelType;
numberOfContrasts = problemDef.numberOfContrasts;
preAlloc = zeros(numberOfContrasts,1);
% Pre-allocate the output arrays..
problem = struct('ssubs',preAlloc,...
                 'backgrounds',preAlloc,...
                 'qshifts',preAlloc,...
                 'scalefactors',preAlloc,...
                 'nbairs',preAlloc,...
                 'nbsubs',preAlloc,...
                 'resolutions',preAlloc,...
                 'calculations',struct('all_chis',preAlloc,'sum_chi',0),...
                 'allSubRough',preAlloc);
reflectivity = cell(numberOfContrasts,1);
for i = 1:numberOfContrasts
    reflectivity{i} = [1 1 ; 1 1];
end
Simulation = cell(numberOfContrasts,1);
for i = 1:numberOfContrasts
    Simulation{i} = [1 1 ; 1 1];
end
shifted_data = cell(numberOfContrasts,1);
for i = 1:numberOfContrasts
    shifted_data{i} = [1 1 1 ; 1 1 1];
end
layerSlds = cell(numberOfContrasts,1);
for i = 1:numberOfContrasts
    layerSlds{i} = [1 1 1 ; 1 1 1];
end
sldProfiles = cell(numberOfContrasts,1);
for i = 1:numberOfContrasts
    sldProfiles{i} = [1 1 ; 1 1];
end
allLayers = cell(numberOfContrasts,1);
for i = 1:numberOfContrasts
    allLayers{i} = [1 ; 1];
end
switch type
    case 'layers'
        [problem,reflectivity,Simulation,...
         shifted_data,layerSlds,sldProfiles,...
         allLayers]= standardTF_stanLay_reflectivityCalculation(problemDef,problemDef_cells,problemDef_limits,controls);
    case 'custom layers'
        [problem,reflectivity,Simulation,...
            shifted_data,layerSlds,sldProfiles,...
            allLayers] = standardTF_custLay_reflectivityCalculation(problemDef,problemDef_cells,problemDef_limits,controls);
%    case 'Custom XY'
%        [problem,reflectivity,Simulation,...
%            shifted_data,layerSlds,sldProfiles,...
%            allLayers] = standardTF_custXY_reflectivityCalculation(problemDef,problemDef_cells,problemDef_limits,controls);
end
end