Description of modelTypes
modelTypes
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
modelTypes
This function is called by:
coderEnums This allow enums to be used by coder without redefinition or hardcoding
modelTypes
SUBFUNCTIONS
function s = toStruct()
function v = values()
function e = fromValue(value)
SOURCE CODE
classdef modelTypes < customEnum
    methods (Static)
        function s = toStruct()
            s = customEnum.toStruct(mfilename('class'));
        end
        function v = values()
            v = customEnum.values(mfilename('class'));
        end
        function e = fromValue(value)
            e = customEnum.fromValue(mfilename('class'), value);
        end
    end
    enumeration
      CustomLayers ('custom layers')
      CustomXY ('custom xy')
      StandardLayers ('standard layers')
    end
end