Description of procedures
procedures
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
procedures
This function is called by:
coderEnums This allow enums to be used by coder without redefinition or hardcoding
procedures
SUBFUNCTIONS
function s = toStruct()
function v = values()
function e = fromValue(value)
SOURCE CODE
classdef procedures < customEnum
   methods (Static)
        function s = toStruct()
            s = customEnum.toStruct(mfilename('class'));
        end
        function v = values()
            v = customEnum.values(mfilename('class'));
        end
        function e = fromValue(value)
            e = customEnum.fromValue(mfilename('class'), value);
        end
    end
    enumeration
        Calculate ('calculate')
        Simplex ('simplex')
        DE ('de')
        NS ('ns')
        Dream ('dream')
    end
end