Description of supportedLanguages
supportedLanguages
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
supportedLanguages
This function is called by:
coderEnums This allow enums to be used by coder without redefinition or hardcoding
supportedLanguages
SUBFUNCTIONS
function s = toStruct()
function v = values()
function e = fromValue(value)
SOURCE CODE
classdef supportedLanguages < customEnum
   methods (Static)
        function s = toStruct()
            s = customEnum.toStruct(mfilename('class'));
        end
        function v = values()
            v = customEnum.values(mfilename('class'));
        end
        function e = fromValue(value)
            e = customEnum.fromValue(mfilename('class'), value);
        end
    end
    enumeration
        Cpp ('cpp')
        Matlab ('matlab')
        Python ('python')
    end
end