Description of refCalc_callFun
refCalc_callFun
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
problemDef
reflectivity_calculation Preallocatin of outputs
reflectivity_calculation Preallocatin of outputs
reflectivity_calculation global RAT_DEBUG DEBUGVARS
reflectivity_calculation
reflectivity_calculation
reflectivity_calculation
This function is called by:
SOURCE CODE
global RAT_DEBUG DEBUGVARS
RAT_DEBUG = 0;
DEBUGVARS = 0;
%callParams = load('callParams.mat');
%callParams = load('newInputs_AL.mat');
%callParams = callParams.newInputs;
% callParams = load('newVars.mat');
% callParams = callParams.newVars;
callParams = load('callVars_latest.mat');
%callParams.callVars.problemDef.modelLanguage = 'matlab';
callParams = callParams.callVars;
% callParams = load('customVars.mat');
% callParams = callParams.customVars;
problemDef = callParams.problemDef;
problemDef_cells = callParams.problemDef_cells;
problemDef_limits = callParams.problemDef_limits;
controls = callParams.controls;
% fn = problemDef.modelFilename;
% [p,n,e] = fileparts(fn);
% problemDef.modelFilename = n;
probleDef.modelFilename = ' ';
[problem,result] = reflectivity_calculation(problemDef,problemDef_cells,problemDef_limits,controls);