Description of reflectivity_calculation_wrapper
reflectivity_calculation_wrapper
PURPOSE
This is just a wrapper function for choosing between
SYNOPSIS
function [problem,result] = reflectivity_calculation_wrapper(problemDef,problemDef_cells,problemDef_limits,controls)
DESCRIPTION
 This is just a wrapper function for choosing between
 the Matlab and Mex version of reflectivity_calculation.
 This is for development and will be removed for the
 eventual fully compiled toolbox
CROSS-REFERENCE INFORMATION
This function calls:
problemDef
reflectivity_calculation Preallocatin of outputs
reflectivity_calculation Preallocatin of outputs
reflectivity_calculation global RAT_DEBUG DEBUGVARS
reflectivity_calculation
reflectivity_calculation
reflectivity_calculation
This function is called by:
singleCalculation Just call the reflectivity calculation.
SOURCE CODE
function [problem,result] = reflectivity_calculation_wrapper(problemDef,problemDef_cells,problemDef_limits,controls)
% This is just a wrapper function for choosing between
% the Matlab and Mex version of reflectivity_calculation.
% This is for development and will be removed for the
% eventual fully compiled toolbox
type = 'mstlab';
 switch type
     case 'mex'
        [problem,result] = reflectivity_calculation_mex(problemDef,problemDef_cells,problemDef_limits,controls);
     otherwise
        [problem,result] = reflectivity_calculation(problemDef,problemDef_cells,problemDef_limits,controls);
end
end