Description of standard_layers_mod
standard_layers_mod
PURPOSE
SYNOPSIS
function [layersOutput,sRoughOutput] = standard_layers_mod(params,contrastLayers,numberOfLayers,layersDetails)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
callModules
callModules
standardLayersMain
standardLayersMain
standard_layers_mod_makeMex UNTITLED Generate static library standard_layers_mod from
standard_layers_mod_makeMex UNTITLED Generate static library standard_layers_mod from
call_StandardLayers
call_StandardLayers (params,i,contrastLayers{i},numberOfLayers,layersDetails,geometry,nbairs,nbsubs);
call_StandardLayers (params,i,contrastLayers{i},numberOfLayers,layersDetails,geometry,nbairs,nbsubs);
call_StandardLayers (params,i,contrastLayers{i},numberOfLayers,layersDetails,geometry,nbairs,nbsubs);
SOURCE CODE
function [layersOutput,sRoughOutput] = standard_layers_mod(params,contrastLayers,numberOfLayers,layersDetails)
sRoughOutput = params(1);
if numberOfLayers == 0
    sub_rough = params(1);
    layersList = [];
else
    layersValues = zeros(numberOfLayers,5);
    for n = 1:numberOfLayers
        thisLayer = layersDetails{n};
        for m = 1:4
            thisItem = thisLayer(m);
            if ~isnan(thisItem)
                layersValues(n,m) = params(thisItem);
            else
                layersValues(n,m) = NaN;
            end
        end
        whichBulk = thisLayer(5);
        if whichBulk == 2
            layersValues(n,5) = 1;
        else
            layersValues(n,5) = 0;
        end
    end
    if ~isempty(contrastLayers)
        layersList = zeros(length(contrastLayers),5);
        for n = 1:length(contrastLayers)
            thisRow = contrastLayers(n);
            layersList(n,:) = layersValues(thisRow,:);
        end
    else
        layersList = [];
    end
end
sub_rough = params(1);
layersOutput = layersList;
sRoughOutput = sub_rough;
end