Description of standardLayersMain
standardLayersMain
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
legacyChanges
legacyChanges
legacyChanges
legacyChanges
legacyChanges
legacyChanges
legacyChanges
legacyChanges
legacyChanges
legacyChanges
legacyChanges
standard_layers_mod
standard_layers_mod
This function is called by:
SOURCE CODE
a = load('testProblem.mat');
problem = a.problem;
problem = legacyChanges(problem);
params = problem.params;
%contrastLayers = problem.contrastLayers;
contrastLayers = problem.contrastLayers{1};
numberOfLayers = problem.numberOfLayers;
layersDetails = problem.layersDetails;
[layersList,sRoughs] = standard_layers_mod(params,contrastLayers,numberOfLayers,layersDetails);