Description of fitsetup
fitsetup
PURPOSE
SYNOPSIS
function [problemDef,out] = fitsetup(problemDef,problemDef_cells,problemDef_limits,controls)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
packparams Separate out the params array into fitting
This function is called by:
runDE
fitcontrol
runSimplex
SOURCE CODE
function [problemDef,out] = fitsetup(problemDef,problemDef_cells,problemDef_limits,controls)
if isfield(controls,'checks')
    checks = controls.checks;
else
    checks.params_fitYesNo = ones(length(problemDef.params),1);
    checks.backs_fitYesNo = ones(length(problemDef.backs),1);
    checks.shifts_fitYesNo = ones(length(problemDef.shifts),1);
    checks.scales_fitYesNo = ones(length(problemDef.sf),1);
    checks.nbairs_fitYesNo = ones(length(problemDef.nba),1);
    checks.nbsubs_fitYesNo = ones(length(problemDef.nbs),1);
    checks.resol_fitYesNo = ones(length(problemDef.res),1);
end
problemDef = packparams(problemDef,problemDef_cells,problemDef_limits,checks);
out = 0;
%Check the bounds on all the selected
% out = checkBounds(problemDef,controls);
% if strcmp(out{1},'fail')
%     return
% end