Description of algaefun
algaefun
PURPOSE
algae model function
SYNOPSIS
function y=algaefun(time,theta,y0,xdata)
DESCRIPTION
 algae model function
CROSS-REFERENCE INFORMATION
This function calls:
algaesys ode system function for MCMC algae example
This function is called by:
algaeex %
algaess algae sum-of-squares function
SOURCE CODE
function y=algaefun(time,theta,y0,xdata)
% algae model function
[t,y] = ode15s(@algaesys,time,y0,[],theta,xdata);