function [reflectivity,simulation,shiftedData,sldProfile,layers,...
    resampledLayers] = coreCustomXYCalculation(bulkIn,bulkOut,...
    shiftedData,simulationXData,dataIndices,resolution,background,...
    backgroundAction,parallel,resampleMinAngle,resampleNPoints,...
    roughness,sld)

    % Resample the layers - always required for a custom XY calculation
    sldProfile = sld(:,[1,2]);
    sldProfileIm = sld(:,[1,3]);
    resampledLayers = resampleLayers(sldProfile,sldProfileIm,...
        resampleMinAngle,resampleNPoints);
    
    layers = resampledLayers;

    reflectivityType = 'standardAbeles';
    [reflectivity,simulation] = callReflectivity(bulkIn,bulkOut,...
     simulationXData,dataIndices,1,layers,roughness,resolution,parallel,...
     reflectivityType);

    [reflectivity,simulation,shiftedData] = applyBackgroundCorrection(...
        reflectivity,simulation,shiftedData,background,backgroundAction);

end