Description of extractProblemParams
extractProblemParams
PURPOSE
Extract individual parameters from problemDef
SYNOPSIS
function [numberOfContrasts, geometry, contrastBackgrounds, contrastQzshifts, contrastScalefactors, contrastBulkIns, contrastBulkOuts,contrastResolutions, backs, shifts, scalefactor, bulkIn, bulkOut, res, dataPresent, nParams, params,numberOfLayers, resample, backsType, contrastCustomFiles] = extractProblemParams(problemDef)
DESCRIPTION
Extract individual parameters from problemDef
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
parallelContrasts Single threaded version of the custom layers, domainsTF reflectivity
parallelPoints Single threaded version of the custom layers, domainsTF reflectivity
single Single threaded version of the custom layers, domainsTF reflectivity
parallelContrasts Extract individual cell arrays
parallelPoints Extract individual cell arrays
single Extract individual cell arrays
parallelContrasts Single threaded version of the Standard Layers calculation
parallelPoints Single threaded version of the Standard Layers calculation
single Single threaded version of the Standard Layers calculation
parallelContrasts Multi threaded version of the custom layers, nonPolarisedTF reflectivity
parallelPoints Multi threaded version of the custom layers over reflectivity poimnts
single Single threaded version of the custom layers, nonPolarisedTF reflectivity
parallelContrasts Extract individual cell arrays
parallelPoints Multi threaded version of the custom XY profile over reflectivity points
single Extract individual cell arrays
parallelContrasts Standard Layers calculation paralelised over the outer loop
parallelPoints Standard Layers calculation paralelised over the inner loop
single Single threaded version of the Standard Layers calculation
SOURCE CODE
function [numberOfContrasts, geometry, contrastBackgrounds, contrastQzshifts, contrastScalefactors, contrastBulkIns, contrastBulkOuts,...
contrastResolutions, backs, shifts, scalefactor, bulkIn, bulkOut, res, dataPresent, nParams, params,...
numberOfLayers, resample, backsType, contrastCustomFiles] =  extractProblemParams(problemDef)
%Extract individual parameters from problemDef
numberOfContrasts = problemDef.numberOfContrasts;
geometry = problemDef.geometry;
contrastBackgrounds = problemDef.contrastBackgrounds;
contrastQzshifts = problemDef.contrastQzshifts;
contrastScalefactors = problemDef.contrastScalefactors;
contrastBulkIns = problemDef.contrastBulkIns;
contrastBulkOuts = problemDef.contrastBulkOuts;
contrastResolutions = problemDef.contrastResolutions;
backs = problemDef.backgroundParams;
shifts = problemDef.qzshifts;
scalefactor = problemDef.scalefactors;
bulkIn = problemDef.bulkIn;
bulkOut = problemDef.bulkOut;
res = problemDef.resolutionParams;
dataPresent = problemDef.dataPresent;
nParams = length(problemDef.params);
params = problemDef.params;
numberOfLayers = problemDef.numberOfLayers;
resample = problemDef.resample;
backsType = problemDef.contrastBackgroundsType;
contrastCustomFiles = problemDef.contrastCustomFiles;
end