Description of SpecialEventDataClass
SpecialEventDataClass
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
SpecialEventDataClass
This function is called by:
SpecialEventDataClass
ratOutputClass
SUBFUNCTIONS
function eventData = SpecialEventDataClass(value)
SOURCE CODE
classdef (ConstructOnLoad) SpecialEventDataClass < event.EventData
   properties
      ratUpdateData
   end
   methods
      function eventData = SpecialEventDataClass(value)
         eventData.ratUpdateData = value;
      end
   end
end