% Analysis of DSPC monolayers Data

% First make an instance of the project class
problem = projectClass('DSPC monolayers');


% Define the parameters:
Parameters = {
    %       Name                min     val     max     fit? 
    {'Tails Thickness',         10,     20,     30,     true};
    {'Heads Thickness',          6,     11,     16,     true};
    {'Tails Roughness',          2,     5,      9,      true};
    {'Heads Roughness',          2,     5,      9,      true};
    {'Deuterated Tails SLD',    4e-6,   6e-6,   8e-6,   true};
    {'Hydrogenated Tails SLD', -0.6e-6, -0.4e-6, 0,     true};
    {'Deuterated Heads SLD',    3e-6,   3e-6,   5e-6,   true};
    {'Hydrogenated Heads SLD',  1e-6,   1.4e-6, 3e-6,   true};
    {'Heads Hydration',         0,      0.3,   0.5,    true};
    {'Tails Hydration',         0,      0,      0,      false};
    };

% Group these into layers:
H_Heads = {'Hydrogenated Heads',...
                'Heads Thickness',...
                'Hydrogenated Heads SLD',...
                'Heads Roughness',...
                'Heads Hydration',...
                'bulk out' };
            
D_Heads = {'Deuterated Heads',...
                'Heads Thickness',...
                'Deuterated Heads SLD',...
                'Heads Roughness',...
                'Heads Hydration',...
                'bulk out' };
            
            
D_Tails = {'Deuterated Tails',...
                'Tails Thickness',...
                'Deuterated Tails SLD',...
                'Tails Roughness',...
                'Tails Hydration',...
                'bulk in'};

H_Tails = {'Hydrogenated Tails',...
                'Tails Thickness',...
                'Deuterated Tails SLD',...
                'Tails Roughness',...
                'Tails Hydration',...
                'bulk in'};


% Add the parameters and Layers to the project:
problem.addParamGroup(Parameters);
problem.addLayerGroup({H_Heads; D_Heads; H_Tails; D_Tails});

% Use priors in the project
problem.setUsePriors(true);

% Need two backgrounds - one for D2O and for H2O
% Change the name of the first and add a new one for the second
% Also need a new backsPar
problem.setBacksParName(1,'Backs value H2O');
problem.addBacksPar('Backs Value D2O');

problem.addBackground('Background D2O','constant','Backs Value D2O');
problem.setBackgroundValue(1,'name','Background H2O');
problem.setBackgroundValue(1,3,'Backs Value H2O');

% Also need an additional bulk out
problem.addBulkOut({'SLD H2O' -0.6e-6,-0.56e-6,-0.5e-6,true});

% Add the 7 contrasts
problem.addContrast('name','H-tail/H-Head/D2O',...
    'background','Background D2O',...
    'resolution','Resolution 1',...
    'nbs', 'SLD D2O',...
    'nba', 'SLD air');
problem.setContrast(1,'model',{'hydrogenated tails','hydrogenated heads'});

problem.addContrast('name','H-tail/D-Head/D2O',...
    'background','Background D2O',...
    'resolution','Resolution 1',...
    'nbs', 'SLD D2O',...
    'nba', 'SLD air');
problem.setContrast(2,'model',{'hydrogenated tails','deuterated heads'});

problem.addContrast('name','D-tail/D-Head/D2O',...
    'background','Background D2O',...
    'resolution','Resolution 1',...
    'nbs', 'SLD D2O',...
    'nba', 'SLD air');
problem.setContrast(3,'model',{'deuterated tails','deuterated heads'});

problem.addContrast('name','H-tail/H-Head/H2O',...
    'background','Background H2O',...
    'resolution','Resolution 1',...
    'nbs', 'SLD H2O',...
    'nba', 'SLD air');
problem.setContrast(4,'model',{'hydrogenated tails','hydrogenated heads'});

problem.addContrast('name','D-tail/H-Head/H2O',...
    'background','Background H2O',...
    'resolution','Resolution 1',...
    'nbs', 'SLD H2O',...
    'nba', 'SLD air');
problem.setContrast(5,'model',{'deuterated tails','hydrogenated heads'})
