Description of problemDef
problemDef
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
problemDef
This function is called by:
%RAT Separate cells from the problemDef struct...
RAT
RAT_main
RAT_remove_cells
RATparseOutToProblemDef Reconstruct the problemDef class as an output
R1toR2 start by making empty default R2 functions.
parseProblemDefToStruct
oldProblemDef
problemDef
r1ToProblemDef --------------------------------------------------------------------------
singleCalculation Just call the reflectivity calculation.
standardTF_custlay_paraPoints Extract individual cell arrays
standardTF_custlay_paraPoints Extract individual cell arrays
standardTF_custlay_single Extract individual cell arrays
standardTF_custlay_single Extract individual cell arrays
standardTF_custLay_reflectivityCalculation Pre-allocation - It's necessary to
standardTF_reflectivityCalculation Decide what kind of calculation it is and call the appropriate one
standardTF_stanlay_paraAll Extract individual cell arrays
standardTF_stanlay_paraAll Extract individual cell arrays
standardTF_stanlay_paraAll Extract individual cell arrays
standardTF_stanlay_paraContrasts Extract individual cell arrays
standardTF_stanlay_paraContrasts Extract individual cell arrays
standardTF_stanlay_paraContrasts Extract individual cell arrays
standardTF_stanlay_paraPoints Extract individual cell arrays
standardTF_stanlay_paraPoints Extract individual cell arrays
standardTF_stanlay_paraPoints Extract individual cell arrays
standardTF_stanlay_single Extract individual cell arrays
standardTF_stanlay_single Extract individual cell arrays
standardTF_stanlay_single Extract individual cell arrays
standardTF_stanLay_reflectivityCalculation Pre-allocation - It's necessary to
SUBFUNCTIONS
function obj = set.experimentType(obj,val)
function obj = set.experimentGeometry(obj,val)
function obj = set.nParams(obj,nParams)
function obj = set.params(obj,val)
function obj = set.paramNames(obj,val)
function obj = set.paramFitYesNo(obj,val)
function obj = set.paramConstr(obj,val)
function obj = set.nBackgrounds(obj,nBackgrounds)
function obj = set.backgrounds(obj,val)
function obj = set.backgroundFitYesNo(obj,val)
function obj = set.backgroundNames(obj,val)
function obj = set.backgroundConstr(obj,val)
function obj = set.nScalefactors(obj,nScalefactors)
function obj = set.scalefactors(obj,val)
function obj = set.scalefactorNames(obj,val)
function obj = set.scalefactorFitYesNo(obj,val)
function obj = set.scalefactorConstr(obj,val)
function obj = set.nQzshifts(obj,nQzshifts)
function obj = set.qzshifts(obj,val)
function obj = set.qzshiftNames(obj,val)
function obj = set.qzshiftFitYesNo(obj,val)
function obj = set.qzshiftConstr(obj,val)
function obj = set.nNbairs(obj,nNbairs)
function obj = set.nbairs(obj,val)
function obj = set.nbairNames(obj,val)
function obj = set.nbairFitYesNo(obj,val)
function obj = set.nbairConstr(obj,val)
function obj = set.nNbsubs(obj,nNbsubs)
function obj = set.nbsubs(obj,val)
function obj = set.nbsubNames(obj,val)
function obj = set.nbsubFitYesNo(obj,val)
function obj = set.nbsubConstr(obj,val)
function obj = set.nResolutions(obj,nResolutions)
function obj = set.resolutions(obj,val)
function obj = set.resolutionNames(obj,val)
function obj = set.resolutionFitYesNo(obj,val)
function obj = set.resolutionConstr(obj,val)
function obj = set.numberOfContrasts(obj,nContrasts)
function obj = set.allData(obj,val)
function obj = set.resample(obj,val)
function obj = set.dataPresent(obj,val)
function obj = set.dataLimits(obj,val)
function obj = set.simLimits(obj,val)
function obj = set.contrastBacks(obj,val)
function obj = set.contrastShifts(obj,val)
function obj = set.contrastScales(obj,val)
function obj = set.contrastNbas(obj,val)
function obj = set.contrastNbss(obj,val)
function obj = set.contrastRes(obj,val)
function obj = set.contrastRepeatSLDs(obj,val)
function obj = set.modelType(obj,val)
function obj = set.numberOfLayers(obj,val)
function obj = set.layersDetails(obj,val)
function obj = set.modelFilename(obj,val)
function obj = set.modelLanguage(obj,val)
function obj = extendNParams(obj,val)
function obj = contractNParams(obj,val)
function obj = extendNResample(obj,val)
function obj = contractNResample(obj,val)
function obj = extendNDataPresent(obj,val)
function obj = contractNDataPresent(obj,val)
function obj = extendNParamNames(obj,val)
function obj = contractNParamNames(obj,val)
function obj = extendNParamConstr(obj,val)
function obj = contractNParamConstr(obj,val)
function obj = extendNParamFitYesNo(obj,val)
function obj = contractNParamFitYesNo(obj,val)
function obj = extendNBackgrounds(obj,val)
function obj = contractNBackgrounds(obj,val)
function obj = extendNBackgroundNames(obj,val)
function obj = contractNBackgroundNames(obj,val)
function obj = extendNBackgroundConstr(obj,val)
function obj = contractNBackgroundConstr(obj,val)
function obj = extendNBackgroundFitYesNo(obj,val)
function obj = contractNBackgroundFitYesNo(obj,val)
function obj = extendNScalefactors(obj,val)
function obj = contractNScalefactors(obj,val)
function obj = extendNScalefactorNames(obj,val)
function obj = contractNScalefactorNames(obj,val)
function obj = extendNScalefactorConstr(obj,val)
function obj = contractNScalefactorConstr(obj,val)
function obj = extendNScalefactorFitYesNo(obj,val)
function obj = contractNScalefactorFitYesNo(obj,val)
function obj = extendNQzshifts(obj,val)
function obj = contractNQzshifts(obj,val)
function obj = extendNQzshiftNames(obj,val)
function obj = contractNQzshiftNames(obj,val)
function obj = extendNQzshiftConstr(obj,val)
function obj = contractNQzshiftConstr(obj,val)
function obj = extendNQzshiftFitYesNo(obj,val)
function obj = contractNQzshiftFitYesNo(obj,val)
function obj = extendNNbairs(obj,val)
function obj = contractNNbairs(obj,val)
function obj = extendNNbairNames(obj,val)
function obj = contractNNbairNames(obj,val)
function obj = extendNNbairConstr(obj,val)
function obj = contractNNbairConstr(obj,val)
function obj = extendNNbairFitYesNo(obj,val)
function obj = contractNNbairFitYesNo(obj,val)
function obj = extendNNbsubs(obj,val)
function obj = contractNNbsubs(obj,val)
function obj = extendNNbsubNames(obj,val)
function obj = contractNNbsubNames(obj,val)
function obj = extendNNbsubConstr(obj,val)
function obj = contractNNbsubConstr(obj,val)
function obj = extendNNbsubFitYesNo(obj,val)
function obj = contractNNbsubFitYesNo(obj,val)
function obj = extendNResolutions(obj,val)
function obj = contractNReslutions(obj,val)
function obj = extendNResolutionsNames(obj,val)
function obj = contractNResolutionsNames(obj,val)
function obj = extendNResolutionsConstr(obj,val)
function obj = contractNResolutionConstr(obj,val)
function obj = extendNResolutionFitYesNo(obj,val)
function obj = contractNResolutionFitYesNo(obj,val)
function obj = extendAllData(obj,val)
function obj = contractAllData(obj,val)
function obj = extendNDataLimits(obj,val)
function obj = contractNDataLimits(obj,val)
function obj = extendNSimLimits(obj,val)
function obj = contractNSimLimits(obj,val)
function obj = extendNContrastBacks(obj,val)
function obj = contractNContrastBacks(obj,val)
function obj = extendNContrastShifts(obj,val)
function obj = contractNContrastShifts(obj,val)
function obj = extendNContrastScales(obj,val)
function obj = contractNContrastScales(obj,val)
function obj = extendNContrastNbas(obj,val)
function obj = contractNContrastNbas(obj,val)
function obj = extendNContrastNbss(obj,val)
function obj = contractNContrastNbss(obj,val)
function obj = extendNContrastRes(obj,val)
function obj = contractNContrastRes(obj,val)
function obj = extendNContrastRepeatSLDs(obj,val)
function obj = contractNContrastRepeatSLDs(obj,val)
function obj = extendNLayersDetails(obj,val)
function obj = extendNContrastLayers(obj,val)
function obj = contractNContrastLayers(obj,val)
function groups = getPropertyGroups(obj)
SOURCE CODE
classdef problemDef < matlab.mixin.CustomDisplay
    properties
    %Experiment
        experimentType = 'standard';
        experimentGeometry = 'substrate/liquid';
        %modelType
    %All parameters
        nParams = 1;
        params = [3];
        paramNames = {'Substrate Roughness'};
        paramConstr = {[1 5]};
        paramFitYesNo = [1];
        nBackgrounds = 1
        backgrounds = [1e-7];
        backgroundNames = {'Background 1'};
        backgroundConstr = {[1e-8 1e-6]};
        backgroundFitYesNo = [0];
        nScalefactors = 1
        scalefactors = [1];
        scalefactorNames = {'Scalefactor 1'};
        scalefactorConstr = {[0.9 1.0]};
        scalefactorFitYesNo = [0];
        nQzshifts = 1
        qzshifts = [0.0];
        qzshiftNames = {'Qzshift 1'};
        qzshiftConstr = {[1e-4 1e4]};
        qzshiftFitYesNo = [0];
        nNbairs = 1
        nbairs = [0];
        nbairNames = {'Air'};
        nbairConstr = {[-1e-8 1e-8]};
        nbairFitYesNo = [0];
        nNbsubs = 1
        nbsubs = [6.35e-6];
        nbsubNames = {'D2O'};
        nbsubConstr = {[6.3e-6 6.4e-6]};
        nbsubFitYesNo = 0;
        nResolutions = 1
        resolutions = [0.03];
        resolutionNames = {'Resol 1'};
        resolutionConstr = {[0.02 0.04]};
        resolutionFitYesNo = [0];
    %Constrasts and Data
        numberOfContrasts = 1
        resample = [0];
        allData = {};
        dataPresent = [0];
        dataLimits = {};
        simLimits = {[0.01 0.7]};
        contrastBacks = {};
        contrastShifts = [1];
        contrastScales = [1];
        contrastNbas = [1];
        contrastNbss = [1];
        contrastRes = [1];
        contrastRepeatSLDs;% = {[0 1]};
    %Model
        modelType = 'layers'
        numberOfLayers = 0;
        layersDetails = {};
        contrastLayers = {};
        modelFilename = '';
        modelLanguage = 'octave';
    end
    methods
        %Experiment block
        function obj = set.experimentType(obj,val)
           if ~strcmpi(val,{'standard','oil-water','PA','domains'})
               error('Type must be ''standard'',''oil-water'',''PA'' or ''domains'' ');
           end
           obj.experimentType = val;
        end
        function obj = set.experimentGeometry(obj,val)
           if ~strcmpi(val,{'air/substrate','substrate/liquid'})
               error('Type must be ''air/substrate'' or ''substrate/liquid'' ');
           end
           obj.experimentGeometry = val;
        end
        %Parameters block
        function obj = set.nParams(obj,nParams)
            if (isnan(nParams) || isinf(nParams) || mod(nParams,1) ~= 0)
                error('nParams must be real integer');
            end
            obj.nParams = nParams;
            if isempty(obj.params)
                obj.params = zeros(1,nParams);
            elseif (length(obj.params) < nParams)
                obj = obj.extendNParams(nParams);
            elseif (length(obj.params) > nParams)
                obj = obj.contractNParams(nParams);
            end
            if isempty(obj.paramNames)
                obj.paramNames = cell(1,nParams);
            elseif (length(obj.paramNames) < nParams)
                obj = obj.extendNParamNames(nParams);
            elseif (length(obj.paramNames) > nParams)
                obj = obj.contractNParamNames(nParams);
            end
            if isempty(obj.paramConstr)
                obj.paramConstr = cell(1,nParams);
            elseif (length(obj.paramConstr) < nParams)
                obj = obj.extendNParamConstr(nParams);
            elseif (length(obj.paramConstr) > nParams)
               obj = obj.contractNParamConstr(nParams);
            end
            if isempty(obj.paramFitYesNo)
                obj.paramFitYesNo = ones(1,nParams);
            elseif (length(obj.paramFitYesNo) < nParams)
                obj = obj.extendNParamFitYesNo(nParams);
            elseif (length(obj.paramFitYesNo) > nParams)
               obj = obj.contractNParamFitYesNo(nParams);
            end
        end
        function obj = set.params(obj,val)
            if (length(val) > obj.nParams)
               error('Length of values vector must be <= nparams');
            elseif (isnumeric(val) == false | isinteger(val) == true)
                error('Params must be vector of doubles');
            else
               obj.params = val;
            end
        end
        function obj = set.paramNames(obj,val)
            if (length(val) > obj.nParams)
               error('Length of paramNames vector must be <= nparams');
            elseif (iscell(val) == false)
               error('paramNames must be cell array');
             else
               obj.paramNames = val;
            end
        end
        function obj = set.paramFitYesNo(obj,val)
          if (length(val) > obj.nParams)
               error('Length of paramFitYesNo vector must be <= nparams');
            elseif (isnumeric(val) == false || sum(ismember(val,[0 1]))~= obj.nParams)
               error('paramsFitYesNo  must be either 0 or 1.');
             else
               obj.paramFitYesNo = val;
            end
        end
        function obj = set.paramConstr(obj,val)
            if (length(val) > obj.nParams)
                error('Length of poramConstr vector must be <= nParams');
            elseif (iscell(val) == false)
                error('paramConstr must be cell array');
            else
                for i = 1:length(val)
                    thisVal = val{i};
                    if isempty(thisVal)
                        val{i} = [0  0];
                    elseif (~isnumeric(thisVal) || (size(thisVal,1)~=1 || size(thisVal,2)~=2) || isinteger(val))
                        error('value %d in assignment to paramConstr must be 1x2 double',i);
                    end
                end
            end
            obj.paramConstr = val;
        end
        %End parameters block
        %-----------------------------------------------------------------------
        %Backgrounds block
        function obj = set.nBackgrounds(obj,nBackgrounds)
            if (isnan(nBackgrounds) || isinf(nBackgrounds) || mod(nBackgrounds,1) ~= 0)
                error('nBackgrounds must be real integer');
            end
            obj.nBackgrounds = nBackgrounds;
            if isempty(obj.backgrounds)
                obj.backgrounds = zeros(1,nBackgrounds);
            elseif (length(obj.backgrounds) < nBackgrounds)
                obj = obj.extendNBackgrounds(nBackgrounds);
            elseif (length(obj.backgrounds) > nBackgrounds)
                obj = obj.contractNBackgrounds(nBackgrounds);
            end
            if isempty(obj.backgroundNames)
                obj.backgroundNames = cell(1,nBackgrounds);
            elseif (length(obj.backgroundNames) < nBackgrounds)
                obj = obj.extendNBackgroundNames(nBackgrounds);
            elseif (length(obj.backgroundNames) > nBackgrounds)
                obj = obj.contractNBackgroundNames(nBackgrounds);
            end
            if isempty(obj.backgroundConstr)
                obj.backgroundConstr = cell(1,nBackgrounds);
            elseif (length(obj.backgroundConstr) < nBackgrounds)
                obj = obj.extendNBackgroundConstr(nBackgrounds);
            elseif (length(obj.backgroundConstr) > nBackgrounds)
               obj = obj.contractNBackgroundConstr(nBackgrounds);
            end
            if isempty(obj.backgroundFitYesNo)
                obj.backgroundFitYesNo = ones(1,nBackgrounds);
            elseif (length(obj.backgroundFitYesNo) < nBackgrounds)
                obj = obj.extendNBackgroundFitYesNo(nBackgrounds);
            elseif (length(obj.backgroundFitYesNo) > nBackgrounds)
               obj = obj.contractNBackgroundFitYesNo(nBackgrounds);
            end
        end
        function obj = set.backgrounds(obj,val)
            if (length(val) > obj.nBackgrounds)
               error('Length of values vector must be <= nbackground');
            elseif (isnumeric(val) == false || isinteger(val) == true)
                error('backgrounds must be vector of doubles');
            else
               obj.backgrounds = val;
            end
        end
        function obj = set.backgroundFitYesNo(obj,val)
          if (length(val) > obj.nBackgrounds)
               error('Length of backgroundFitYesNo vector must be <= nparams');
            elseif (isnumeric(val) == false || sum(ismember(val,[0 1]))~= obj.nBackgrounds)
               error('paramsFitYesNo  must be either 0 or 1.');
             else
               obj.backgroundFitYesNo = val;
            end
        end
        function obj = set.backgroundNames(obj,val)
            if (length(val) > obj.nBackgrounds)
               error('Length of backgroundNames vector must be <= nbackground');
            elseif (iscell(val) == false)
               error('backgroundNames must be cell array');
             else
               obj.backgroundNames = val;
            end
        end
        function obj = set.backgroundConstr(obj,val)
            if (length(val) > obj.nBackgrounds)
                error('Length of poramConstr vector must be <= nbackground');
            elseif (iscell(val) == false)
                error('backgroundConstr must be cell array');
            else
                for i = 1:length(val)
                    thisVal = val{i};
                    if isempty(thisVal)
                        val{i} = [0  0];
                    elseif (~isnumeric(thisVal) || (size(thisVal,1)~=1 || size(thisVal,2)~=2) || isinteger(val))
                        error('value %d in assignment to backgroundConstr must be 1x2 double',i);
                    end
                end
            end
            obj.backgroundConstr = val;
        end
    %End backgrounds block
    %----------------------------------------------------------------------
    %scalefactors block
        function obj = set.nScalefactors(obj,nScalefactors)
            if (isnan(nScalefactors) || isinf(nScalefactors) || mod(nScalefactors,1) ~= 0)
                error('nScalefactors must be real integer');
            end
            obj.nScalefactors = nScalefactors;
            if isempty(obj.scalefactors)
                obj.scalefactors = zeros(1,nScalefactors);
            elseif (length(obj.scalefactors) < nScalefactors)
                obj = obj.extendnScalefactors(nScalefactors);
            elseif (length(obj.scalefactors) > nScalefactors)
                obj = obj.contractNScalefactors(nScalefactors);
            end
            if isempty(obj.scalefactorNames)
                obj.scalefactorNames = cell(1,nScalefactors);
            elseif (length(obj.scalefactorNames) < nScalefactors)
                obj = obj.extendNScalefactorNames(nScalefactors);
            elseif (length(obj.scalefactorNames) > nScalefactors)
                obj = obj.contractNScalefactorNames(nScalefactors);
            end
            if isempty(obj.scalefactorConstr)
                obj.scalefactorConstr = cell(1,nScalefactors);
            elseif (length(obj.scalefactorConstr) < nScalefactors)
                obj = obj.extendNScalefactorConstr(nScalefactors);
            elseif (length(obj.scalefactorConstr) > nScalefactors)
               obj = obj.contractNScalefactorConstr(nScalefactors);
            end
            if isempty(obj.scalefactorFitYesNo)
                obj.scalefactorFitYesNo = ones(1,nScalefactors);
            elseif (length(obj.scalefactorFitYesNo) < nScalefactors)
                obj = obj.extendNScalefactorFitYesNo(nScalefactors);
            elseif (length(obj.scalefactorFitYesNo) > nScalefactors)
               obj = obj.contractNScalefactorFitYesNo(nScalefactors);
            end
        end
        function obj = set.scalefactors(obj,val)
            if (length(val) > obj.nScalefactors)
               error('Length of values vector must be <= nscalefactor');
            elseif (isnumeric(val) == false || isinteger(val) == true)
                error('scalefactors must be vector of doubles');
            else
               obj.scalefactors = val;
            end
        end
        function obj = set.scalefactorNames(obj,val)
            if (length(val) > obj.nScalefactors)
               error('Length of scalefactorNames vector must be <= nscalefactor');
            elseif (iscell(val) == false)
               error('scalefactorNames must be cell array');
             else
               obj.scalefactorNames = val;
            end
        end
        function obj = set.scalefactorFitYesNo(obj,val)
          if (length(val) > obj.nScalefactors)
               error('Length of scalefactorFitYesNo vector must be <= nparams');
            elseif (isnumeric(val) == false || sum(ismember(val,[0 1]))~= obj.nScalefactors)
               error('scalefactorFitYesNo  must be either 0 or 1.');
             else
               obj.scalefactorFitYesNo = val;
            end
        end
        function obj = set.scalefactorConstr(obj,val)
            if (length(val) > obj.nScalefactors)
                error('Length of poramConstr vector must be <= nscalefactor');
            elseif (iscell(val) == false)
                error('scalefactorConstr must be cell array');
            else
                for i = 1:length(val)
                    thisVal = val{i};
                    if isempty(thisVal)
                        val{i} = [0  0];
                    elseif (~isnumeric(thisVal) || (size(thisVal,1)~=1 || size(thisVal,2)~=2) || isinteger(val))
                        error('value %d in assignment to scalefactorConstr must be 1x2 double',i);
                    end
                end
            end
            obj.scalefactorConstr = val;
        end
    %End scalefactors block
    %----------------------------------------------------------------------
    %qzshifts block
        function obj = set.nQzshifts(obj,nQzshifts)
            if (isnan(nQzshifts) || isinf(nQzshifts) || mod(nQzshifts,1) ~= 0)
                error('nQzshifts must be real integer');
            end
            obj.nQzshifts = nQzshifts;
            if isempty(obj.qzshifts)
                obj.qzshifts = zeros(1,nQzshifts);
            elseif (length(obj.qzshifts) < nQzshifts)
                obj = obj.extendnQzshifts(nQzshifts);
            elseif (length(obj.qzshifts) > nQzshifts)
                obj = obj.contractNQzshifts(nQzshifts);
            end
            if isempty(obj.qzshiftNames)
                obj.qzshiftNames = cell(1,nQzshifts);
            elseif (length(obj.qzshiftNames) < nQzshifts)
                obj = obj.extendNqzshiftNames(nQzshifts);
            elseif (length(obj.qzshiftNames) > nQzshifts)
                obj = obj.contractNQzshiftNames(nQzshifts);
            end
            if isempty(obj.qzshiftConstr)
                obj.qzshiftConstr = cell(1,nQzshifts);
            elseif (length(obj.qzshiftConstr) < nQzshifts)
                obj = obj.extendNqzshiftConstr(nQzshifts);
            elseif (length(obj.qzshiftConstr) > nQzshifts)
               obj = obj.contractNQzshiftConstr(nQzshifts);
            end
            if isempty(obj.qzshiftFitYesNo)
                obj.qzshiftFitYesNo = ones(1,nQzshifts);
            elseif (length(obj.qzshiftFitYesNo) < nQzshifts)
                obj = obj.extendNQzShiftFitYesNo(nQzshifts);
            elseif (length(obj.qzshiftFitYesNo) > nQzshifts)
               obj = obj.contractNQzshiftFitYesNo(nQzshifts);
            end
        end
        function obj = set.qzshifts(obj,val)
            if (length(val) > obj.nQzshifts)
               error('Length of values vector must be <= nqzshift');
            elseif (isnumeric(val) == false | isinteger(val) == true)
                error('qzshifts must be vector of doubles');
            else
               obj.qzshifts = val;
            end
        end
        function obj = set.qzshiftNames(obj,val)
            if (length(val) > obj.nQzshifts)
               error('Length of qzshiftNames vector must be <= nqzshift');
            elseif (iscell(val) == false)
               error('qzshiftNames must be cell array');
             else
               obj.qzshiftNames = val;
            end
        end
        function obj = set.qzshiftFitYesNo(obj,val)
          if (length(val) > obj.nQzshifts)
               error('Length of qzshiftFitYesNo vector must be <= nparams');
            elseif (isnumeric(val) == false || sum(ismember(val,[0 1]))~= obj.nQzshifts)
               error('qzshiftFitYesNo  must be either 0 or 1.');
             else
               obj.qzshiftFitYesNo = val;
            end
        end
        function obj = set.qzshiftConstr(obj,val)
            if (length(val) > obj.nQzshifts)
                error('Length of poramConstr vector must be <= nqzshift');
            elseif (iscell(val) == false)
                error('qzshiftConstr must be cell array');
            else
                for i = 1:length(val)
                    thisVal = val{i};
                    if isempty(thisVal)
                        val{i} = [0  0];
                    elseif (~isnumeric(thisVal) || (size(thisVal,1)~=1 || size(thisVal,2)~=2) || isinteger(val))
                        error('value %d in assignment to qzshiftConstr must be 1x2 double',i);
                    end
                end
            end
            obj.qzshiftConstr = val;
        end
        %End qzshifts block
    %----------------------------------------------------------------------
        %NBairs block
        function obj = set.nNbairs(obj,nNbairs)
            if (isnan(nNbairs) || isinf(nNbairs) || mod(nNbairs,1) ~= 0)
                error('nNbairs must be real integer');
            end
            obj.nNbairs = nNbairs;
            if isempty(obj.nbairs)
                obj.nbairs = zeros(1,nNbairs);
            elseif (length(obj.nbairs) < nNbairs)
                obj = obj.extendNNbairs(nNbairs);
            elseif (length(obj.nbairs) > nNbairs)
                obj = obj.contractNNbairs(nNbairs);
            end
            if isempty(obj.nbairNames)
                obj.nbairNames = cell(1,nNbairs);
            elseif (length(obj.nbairNames) < nNbairs)
                obj = obj.extendNNbairNames(nNbairs);
            elseif (length(obj.nbairNames) > nNbairs)
                obj = obj.contractNNbairNames(nNbairs);
            end
            if isempty(obj.nbairConstr)
                obj.nbairConstr = cell(1,nNbairs);
            elseif (length(obj.nbairConstr) < nNbairs)
                obj = obj.extendNNbairConstr(nNbairs);
            elseif (length(obj.nbairConstr) > nNbairs)
               obj = obj.contractNNbairConstr(nNbairs);
            end
            if isempty(obj.nbairFitYesNo)
                obj.nbairFitYesNo = ones(1,nNbairs);
            elseif (length(obj.nbairFitYesNo) < nNbairs)
                obj = obj.extendNNbairFitYesNo(nNbairs);
            elseif (length(obj.nbairFitYesNo) > nNbairs)
               obj = obj.contractNNbairFitYesNo(nNbairs);
            end
        end
        function obj = set.nbairs(obj,val)
            if (length(val) > obj.nNbairs)
               error('Length of values vector must be <= nnbairs');
            elseif (isnumeric(val) == false || isinteger(val) == true)
                error('Nbairs must be vector of doubles');
            else
               obj.nbairs = val;
            end
        end
        function obj = set.nbairNames(obj,val)
            if (length(val) > obj.nNbairs)
               error('Length of nbairNames vector must be <= nnbairs');
            elseif (iscell(val) == false)
               error('nbairNames must be cell array');
             else
               obj.nbairNames = val;
            end
        end
        function obj = set.nbairFitYesNo(obj,val)
          if (length(val) > obj.nNbairs)
               error('Length of nbairFitYesNo vector must be <= nNbairs');
            elseif (isnumeric(val) == false || sum(ismember(val,[0 1]))~= obj.nNbairs)
               error('nbairFitYesNo  must be either 0 or 1.');
             else
               obj.nbairFitYesNo = val;
            end
        end
        function obj = set.nbairConstr(obj,val)
            if (length(val) > obj.nNbairs)
                error('Length of nbairConstr vector must be <= nNbairs');
            elseif (iscell(val) == false)
                error('nbairConstr must be cell array');
            else
                for i = 1:length(val)
                    thisVal = val{i};
                    if isempty(thisVal)
                        val{i} = [0  0];
                    elseif (~isnumeric(thisVal) || (size(thisVal,1)~=1 || size(thisVal,2)~=2) || isinteger(val))
                        error('value %d in assignment to nbairConstr must be 1x2 double',i);
                    end
                end
            end
            obj.nbairConstr = val;
        end
        %End NBairs block
    %----------------------------------------------------------------------
    %NBsubs block
        function obj = set.nNbsubs(obj,nNbsubs)
            if (isnan(nNbsubs) || isinf(nNbsubs) || mod(nNbsubs,1) ~= 0)
                error('nNbsubs must be real integer');
            end
            obj.nNbsubs = nNbsubs;
            if isempty(obj.nbsubs)
                obj.nbsubs = zeros(1,nNbsubs);
            elseif (length(obj.nbsubs) < nNbsubs)
                obj = obj.extendNNbsubs(nNbsubs);
            elseif (length(obj.nbsubs) > nNbsubs)
                obj = obj.contractNNbsubs(nNbsubs);
            end
            if isempty(obj.nbsubNames)
                obj.nbsubNames = cell(1,nNbsubs);
            elseif (length(obj.nbsubNames) < nNbsubs)
                obj = obj.extendNNbsubNames(nNbsubs);
            elseif (length(obj.nbsubNames) > nNbsubs)
                obj = obj.contractNNbsubNames(nNbsubs);
            end
            if isempty(obj.nbsubConstr)
                obj.nbsubConstr = cell(1,nNbsubs);
            elseif (length(obj.nbsubConstr) < nNbsubs)
                obj = obj.extendNNbsubConstr(nNbsubs);
            elseif (length(obj.nbsubConstr) > nNbsubs)
               obj = obj.contractNNbsubConstr(nNbsubs);
            end
            if isempty(obj.nbsubFitYesNo)
                obj.nbsubFitYesNo = ones(1,nNbsubs);
            elseif (length(obj.nbsubFitYesNo) < nNbsubs)
                obj = obj.extendNNbsubFitYesNo(nNbsubs);
            elseif (length(obj.nbsubFitYesNo) > nNbsubs)
               obj = obj.contractNNbsubFitYesNo(nNbsubs);
            end
        end
        function obj = set.nbsubs(obj,val)
            if (length(val) > obj.nNbsubs)
               error('Length of values vector must be <= nnbsubs');
            elseif (isnumeric(val) == false | isinteger(val) == true)
                error('Nbsubs must be vector of doubles');
            else
               obj.nbsubs = val;
            end
        end
        function obj = set.nbsubNames(obj,val)
            if (length(val) > obj.nNbsubs)
               error('Length of nbsubNames vector must be <= nnbsubs');
            elseif (iscell(val) == false)
               error('nbsubNames must be cell array');
             else
               obj.nbsubNames = val;
            end
        end
        function obj = set.nbsubFitYesNo(obj,val)
          if (length(val) > obj.nNbsubs)
               error('Length of nbsubFitYesNo vector must be <= nparams');
            elseif (isnumeric(val) == false || sum(ismember(val,[0 1]))~= obj.nNbsubs)
               error('nbsubFitYesNo  must be either 0 or 1.');
             else
               obj.nbsubFitYesNo = val;
            end
        end
        function obj = set.nbsubConstr(obj,val)
            if (length(val) > obj.nNbsubs)
                error('Length of poramConstr vector must be <= nNbsubs');
            elseif (iscell(val) == false)
                error('nbsubConstr must be cell array');
            else
                for i = 1:length(val)
                    thisVal = val{i};
                    if isempty(thisVal)
                        val{i} = [0  0];
                    elseif (~isnumeric(thisVal) || (size(thisVal,1)~=1 || size(thisVal,2)~=2) || isinteger(val))
                        error('value %d in assignment to nbsubConstr must be 1x2 double',i);
                    end
                end
            end
            obj.nbsubConstr = val;
        end
        %End NBsubs block
        %----------------------------------------------------------------------
    %Resolutions block
        function obj = set.nResolutions(obj,nResolutions)
            if (isnan(nResolutions) || isinf(nResolutions) || mod(nResolutions,1) ~= 0)
                error('nReslutions must be real integer');
            end
            obj.nResolutions = nResolutions;
            if isempty(obj.resolutions)
                obj.resolutions = zeros(1,nResolutions);
            elseif (length(obj.resolutions) < nResolutions)
                obj = obj.extendNResolutions(nResolutions);
            elseif (length(obj.resolutions) > nResolutions)
                obj = obj.contractNResolutions(nResolutions);
            end
            if isempty(obj.resolutionNames)
                obj.resolutionNames = cell(1,nResolutions);
            elseif (length(obj.resolutionNames) < nResolutions)
                obj = obj.extendNresolutionNames(nResolutions);
            elseif (length(obj.resolutionNames) > nResolutions)
                obj = obj.contractNresolutionNames(nResolutions);
            end
            if isempty(obj.resolutionConstr)
                obj.resolutionConstr = cell(1,nResolutions);
            elseif (length(obj.resolutionConstr) < nResolutions)
                obj = obj.extendNresolutionConstr(nResolutins);
            elseif (length(obj.resolutionConstr) > nResolutions)
               obj = obj.contractNresolutionConstr(nResolutions);
            end
            if isempty(obj.resolutionFitYesNo)
                obj.resolutionFitYesNo = ones(1,nResolutions);
            elseif (length(obj.resolutionFitYesNo) < nResolutions)
                obj = obj.extendNReslutionFitYesNo(nResolutions);
            elseif (length(obj.resolutionFitYesNo) > nResolutions)
               obj = obj.contractNResolutionFitYesNo(nResolutions);
            end
        end
        function obj = set.resolutions(obj,val)
            if (length(val) > obj.nResolutions)
               error('Length of values vector must be <= nResolutions');
            elseif (isnumeric(val) == false || isinteger(val) == true)
                error('Resolutins must be vector of doubles');
            else
               obj.resolutions = val;
            end
        end
        function obj = set.resolutionNames(obj,val)
            if (length(val) > obj.nResolutions)
               error('Length of resolutinsNames vector must be <= nResolutions');
            elseif (iscell(val) == false)
               error('resolutionsNames must be cell array');
             else
               obj.resolutionNames = val;
            end
        end
        function obj = set.resolutionFitYesNo(obj,val)
          if (length(val) > obj.nResolutions)
               error('Length of resolutionFitYesNo vector must be <= nparams');
            elseif (isnumeric(val) == false || sum(ismember(val,[0 1]))~= obj.nResolutions)
               error('reslutionFitYesNo  must be either 0 or 1.');
             else
               obj.resolutionFitYesNo = val;
            end
        end
        function obj = set.resolutionConstr(obj,val)
            if (length(val) > obj.nResolutions)
                error('Length of resolutionsConstr vector must be <= nResolutions');
            elseif (iscell(val) == false)
                error('resolutionsConstr must be cell array');
            else
                for i = 1:length(val)
                    thisVal = val{i};
                    if isempty(thisVal)
                        val{i} = [0  0];
                    elseif (~isnumeric(thisVal) || (size(thisVal,1)~=1 || size(thisVal,2)~=2) || isinteger(val))
                        error('value %d in assignment to resolutionConstr must be 1x2 double',i);
                    end
                end
            end
            obj.resolutionConstr = val;
        end
        %End resolutions block
    %--------------------Contrasts-----------------------------------------
     function obj = set.numberOfContrasts(obj,nContrasts)
            if (isnan(nContrasts) || isinf(nContrasts) || mod(nContrasts,1) ~= 0)
                error('number of contrasts must be real integer');
            end
            obj.numberOfContrasts = nContrasts;
            if isempty(obj.allData)
                obj.allData = cell(1,nContrasts);
            elseif (length(obj.allData) < nContrasts)
                obj = obj.extendAllData(nContrasts);
            elseif (length(obj.allData) > nContrasts)
                obj = obj.contractAllData(nContrasts);
            end
            if isempty(obj.resample)
                obj.resample = ones(1,nContrasts);
            elseif (length(obj.resample) < nContrasts)
                obj = obj.extendNResample(nContrasts);
            elseif (length(obj.resample) > nContrasts)
                obj = obj.contractNResample(nContrasts);
            end
            if isempty(obj.dataPresent)
                obj.dataPresent = ones(1,nContrasts);
            elseif (length(obj.dataPresent) < nContrasts)
                obj = obj.extendNDataPresent(nContrasts);
            elseif (length(obj.dataPresent) > nContrasts)
                obj = obj.contractNDataPresent(nContrasts);
            end
            if isempty(obj.dataLimits)
                obj.dataLimits = cell(1,nContrasts);
            elseif (length(obj.dataLimits) < nContrasts)
                obj = obj.extendNDataLimits(nContrasts);
            elseif (length(obj.dataLimits) > nContrasts)
               obj = obj.contractNDataLimits(nContrasts);
            end
            if isempty(obj.simLimits)
                obj.simLimits = cell(1,nContrasts);
            elseif (length(obj.simLimits) < nContrasts)
                obj = obj.extendNSimLimits(nContrasts);
            elseif (length(obj.simLimits) > nContrasts)
               obj = obj.contractNSimLimits(nContrasts);
            end
            if isempty(obj.contrastBacks)
                obj.contrastBacks = cell(1,nContrasts);
            elseif (length(obj.contrastBacks) < nContrasts)
                obj = obj.extendNContrastBacks(nContrasts);
            elseif (length(obj.contrastBacks) > nContrasts)
               obj = obj.contractNContrastBacks(nContrasts);
            end
            if isempty(obj.contrastShifts)
                obj.contrastShifts = ones(1,nContrasts);
            elseif (length(obj.contrastShifts) < nContrasts)
                obj = obj.extendNContrastShifts(nContrasts);
            elseif (length(obj.contrastShifts) > nContrasts)
               obj = obj.contractNContrastShifts(nContrasts);
            end
            if isempty(obj.contrastScales)
                obj.contrastScales = ones(1,nContrasts);
            elseif (length(obj.contrastScales) < nContrasts)
                obj = obj.extendNContrastScales(nContrasts);
            elseif (length(obj.contrastScales) > nContrasts)
               obj = obj.contractNContrastScales(nContrasts);
            end
            if isempty(obj.contrastNbas)
                obj.contrastNbas = ones(1,nContrasts);
            elseif (length(obj.contrastNbas) < nContrasts)
                obj = obj.extendNContrastNbas(nContrasts);
            elseif (length(obj.contrastNbas) > nContrasts)
               obj = obj.contractNContrastNbas(nContrasts);
            end
            if isempty(obj.contrastNbss)
                obj.contrastNbss = ones(1,nContrasts);
            elseif (length(obj.contrastNbss) < nContrasts)
                obj = obj.extendNContrastNbss(nContrasts);
            elseif (length(obj.contrastNbss) > nContrasts)
               obj = obj.contractNContrastNbss(nContrasts);
            end
            if isempty(obj.contrastRes)
                obj.contrastRes = ones(1,nContrasts);
            elseif (length(obj.contrastRes) < nContrasts)
                obj = obj.extendNContrastRes(nContrasts);
            elseif (length(obj.contrastRes) > nContrasts)
               obj = obj.contractNContrastRes(nContrasts);
            end
            if isempty(obj.resample)
                obj.resample = ones(1,nContrasts);
            elseif (length(obj.resample) < nContrasts)
                obj = obj.extendNResample(nContrasts);
            elseif (length(obj.resample) > nContrasts)
                obj = obj.contractNResample(nContrasts);
            end
            if isempty(obj.contrastLayers)
                obj.contrastLayers = cell(1,nContrasts);
            elseif (length(obj.contrastLayers) < nContrasts)
                obj = obj.extendNContrastLayers(nContrasts);
            elseif (length(obj.contrastLayers) > nContrasts)
               obj = obj.contractNContrastLayers(nContrasts);
            end
            if  isempty(obj.contrastRepeatSLDs)
                obj.contrastRepeatSLDs = cell(1,nContrasts);
            elseif (length(obj.contrastRepeatSLDs) < nContrasts)
                obj = obj.extendNContrastRepeatSLDs(nContrasts);
            elseif (length(obj.contrastRepeatSLDs) > nContrasts)
                obj = obj.contractNContrastRepeatSLDs(nContrasts);
            end
     end
     function obj = set.allData(obj,val)
            if (length(val) > obj.numberOfContrasts)
                error('Number of datasets must be <= number Of Contrasts');
            elseif (iscell(val) == false)
                error('Each dataset must be a cell');
            else
                for i = 1:length(val)
                    thisVal = val{i};
                    if iscell(thisVal)
                        if length(thisVal) ~= 2
                            error('Call must be {''fname'' ''type''} pair');
                        end
                    elseif isnumeric(thisVal)
                        if isempty(thisVal)
                            val{i} = [];
                        elseif (size(thisVal,2)<1 || size(thisVal,2)>4)
                            error('value %d in assignment to allData must be nx(1:4) double',i);
                        end
                    elseif isinteger(thisVal)
                        error('Numeric values of data cannot be integer');
                    end
                end
            end
            obj.allData = val;
     end
     function obj = set.resample(obj,val)
            if (length(val) > obj.numberOfContrasts)
               error('Length of resample vector must be <= numberOfContrasts');
            elseif (isnumeric(val) == false || sum(ismember(val,[0 1]))~=obj.numberOfContrasts)
                error('resample must be 1 or 0');
            elseif (length(val) < obj.numberOfContrasts)
                error('Unindexed assignment - total length resample must = numberOfContrasts');
            else
               obj.resample = val;
            end
     end
    function obj = set.dataPresent(obj,val)
            if (length(val) > obj.numberOfContrasts)
               error('Length of dataPresent vector must be <= numberOfContrasts');
            elseif (isnumeric(val) == false || sum(ismember(val,[0 1]))~=obj.numberOfContrasts)
                error('dataPresent must be 1 or 0');
            elseif (length(val) < obj.numberOfContrasts)
                error('Unindexed assignment - total length dataPresent must = numberOfContrasts');
            else
               obj.dataPresent = val;
            end
     end
     function obj = set.dataLimits(obj,val)
            if (length(val) > obj.numberOfContrasts)
                error('Length of dataLimits array must be <= number of contrasts');
            elseif (iscell(val) == false)
                error('paramConstr must be cell array');
            else
                for i = 1:length(val)
                    thisVal = val{i};
                    if isempty(thisVal)
                        val{i} = [0  0];
                    elseif (~isnumeric(thisVal) || (size(thisVal,1)~=1 || size(thisVal,2)~=2) || isinteger(val))
                        error('value %d in assignment to dataLimits must be 1x2 double',i);
                    end
                end
            end
            obj.dataLimits = val;
      end
      function obj = set.simLimits(obj,val)
            if (length(val) > obj.numberOfContrasts)
                error('Length of simLimits array must be <= numbr of contrasts');
            elseif (iscell(val) == false)
                error('simLimits must be cell array');
            else
                for i = 1:length(val)
                    thisVal = val{i};
                    if isempty(thisVal)
                        val{i} = [0  0];
                    elseif (~isnumeric(thisVal) || (size(thisVal,1)~=1 || size(thisVal,2)~=2) || isinteger(val))
                        error('value %d in assignment to simLimits must be 1x2 double',i);
                    end
                end
            end
            obj.simLimits = val;
        end
%         function obj = set.contrastBacks(obj,val)
%             if (length(val) > obj.numberOfContrasts)
%                error('Length of values vector must be = numberOfContrasts');
%             elseif (isnumeric(val) == false || any(mod(val,1)))
%                 error('backgrounds must be vector of integers');
%             elseif (length(val) < obj.numberOfContrasts)
%                 error('Unindexed assignment - total length contrastBacks must = numberOfContrasts');
%             else
%                obj.contrastBacks = val;
%             end
%         end
        function obj = set.contrastBacks(obj,val)
            if (length(val) > obj.numberOfContrasts)
                error('Length of contrastBackss array must be <= number of contrasts');
            elseif (iscell(val) == false)
                error('contrastBacks must be cell array');
            else
                for i = 1:length(val)
                    thisVal = val{i};
                    if isempty(thisVal)
                        val{i} = [1  1];
                    elseif (~isnumeric(thisVal) || (size(thisVal,1)~=1 || size(thisVal,2)~=2) || isinteger(val))
                        error('value %d in assignment to dataLimits must be 1x2 double',i);
                    end
                end
            end
            obj.contrastBacks = val;
      end
        function obj = set.contrastShifts(obj,val)
            if (length(val) > obj.numberOfContrasts)
               error('Length of values vector must be <= numberOfContrasts');
            elseif (isnumeric(val) == false || any(mod(val,1)))
                error('contrast shifts must be vector of doubles');
            elseif (length(val) < obj.numberOfContrasts)
                error('Unindexed assignment - total length contrastShifts must = numberOfContrasts');
            else
               obj.contrastShifts = val;
            end
1000         end
1001
1002         function obj = set.contrastScales(obj,val)
1003             if (length(val) > obj.numberOfContrasts)
1004                error('Length of values vector must be <= numberOfContrasts');
1005             elseif (isnumeric(val) == false || any(mod(val,1)))
1006                 error('contrast scales must be vector of doubles');
1007             elseif (length(val) < obj.numberOfContrasts)
1008                 error('Unindexed assignment - total length contrastScales must = numberOfContrasts');
1009             else
1010                obj.contrastScales = val;
1011             end
1012         end
1013
1014         function obj = set.contrastNbas(obj,val)
1015             if (length(val) > obj.numberOfContrasts)
1016                error('Length of values vector must be <= numberOfContrasts');
1017             elseif (isnumeric(val) == false || any(mod(val,1)))
1018                 error('contrast Nbas must be vector of doubles');
1019             elseif (length(val) < obj.numberOfContrasts)
1020                 error('Unindexed assignment - total length contrastNbas must = numberOfContrasts');
1021             else
1022                obj.contrastNbas = val;
1023             end
1024         end
1025
1026         function obj = set.contrastNbss(obj,val)
1027             if (length(val) > obj.numberOfContrasts)
1028                error('Length of values vector must be <= numberOfContrasts');
1029             elseif (isnumeric(val) == false || any(mod(val,1)))
1030                 error('contrast Nbas must be vector of doubles');
1031             elseif (length(val) < obj.numberOfContrasts)
1032                 error('Unindexed assignment - total length contrastNbss must = numberOfContrasts');
1033             else
1034                obj.contrastNbss = val;
1035             end
1036         end
1037
1038         function obj = set.contrastRes(obj,val)
1039             if (length(val) > obj.numberOfContrasts)
1040                error('Length of values vector must be <= numberOfContrasts');
1041             elseif (isnumeric(val) == false || any(mod(val,1)))
1042                 error('contrast Nbas must be vector of doubles');
1043             elseif (length(val) < obj.numberOfContrasts)
1044                 error('Unindexed assignment - total length contrastRes must = numberOfContrasts');
1045             else
1046                obj.contrastRes = val;
1047             end
1048         end
1049
1050         function obj = set.contrastRepeatSLDs(obj,val)
1051             if (length(val) > obj.numberOfContrasts)
1052                 error('Length of contrastRepeatSLDs array must be <= number of contrasts');
1053             elseif (iscell(val) == false)
1054                 error('paramConstr must be cell array');
1055             else
1056                 for i = 1:length(val)
1057                     thisVal = val{i};
1058                     if isempty(thisVal)
1059                         val{i} = [0  1];
1060                     elseif (~isnumeric(thisVal) || (size(thisVal,1)~=1 || size(thisVal,2)~=2) || isinteger(val))
1061                         error('value %d in assignment to dataLimits must be 1x2 double',i);
1062                     end
1063                 end
1064             end
1065             obj.contrastRepeatSLDs = val;
1066       end
1067
1068
1069
1070
1071    %--------------- End Contrasts Block ----------------------------------
1072
1073    %Model Block
1074
1075         function obj = set.modelType(obj,val)
1076              if ~ischar(val)
1077                  error('modelType must be char');
1078              end
1079              if ~any(strcmpi(val,{'Layers','Custom Layers','Custom XY'}))
1080                  error('modelType must be ''Layers'', ''Custom Layers'' or ''Custom XY'' ');
1081              end
1082              obj.modelType = val;
1083         end
1084
1085         function obj = set.numberOfLayers(obj,val)
1086             nLayers = val;
1087             if (isnan(nLayers) || isinf(nLayers) || mod(nLayers,1) ~= 0)
1088                 error('number of layers must be real integer');
1089             end
1090             obj.numberOfLayers = val;
1091
1092             if isempty(obj.layersDetails)
1093                 obj.layersDetails = cell(nLayers,1);
1094             elseif (size(obj.nLayers,1) < nLayers)
1095                 obj = obj.extendNLayersDetails(nLayers);
1096             elseif (length(obj.nLayers,1) > nLayers)
1097                 obj = obj.contractNLayersDetails(nLayers);
1098             end
1099         end
1100
1101         function obj = set.layersDetails(obj,val)
1102             if (length(val) > obj.numberOfLayers)
1103                 error('Length of layersDetails array must be <= number of layers');
1104             elseif (iscell(val) == false)
1105                 error('layersDetails must be cell array');
1106             else
1107                 for i = 1:length(val)
1108                     thisVal = val{i};
1109                     if isempty(thisVal)
1110                         val{i} = [1 1 1 0 1];
1111                     elseif (~isnumeric(thisVal) || size(thisVal,2)~=5 || any(mod(thisVal,1))~=0)
1112                         error('value %d in assignment to layersDetails must be 1x5 integer',i);
1113                     end
1114                 end
1115             end
1116             obj.layersDetails = val;
1117         end
1118
1119         function obj = set.modelFilename(obj,val)
1120             if ~ischar(val)
1121                 error('model filename must be a char');
1122             end
1123             obj.modelFilename = val;
1124         end
1125
1126         function obj = set.modelLanguage(obj,val)
1127            if ~strcmpi(val,{'matlab','python'})
1128                error('Model language must be ''matlab'' or ''python'' ');
1129            end
1130            obj.modelLanguage = val;
1131         end
1132
1133     end %Public Methods end
1134
1135     %-----------------------------------------------------------------------
1136
1137     %Utility Functions.
1138     methods (Access = private)
1139
1140
1141     %parameters
1142         function obj = extendNParams(obj,val)
1143            currentLength = length(obj.params);
1144            new = zeros(1,(val-currentLength));
1145            new = [obj.params,new];
1146            obj.params = new;
1147         end
1148
1149         function obj = contractNParams(obj,val)
1150            obj.params = obj.params(1:val);
1151         end
1152
1153         function obj = extendNResample(obj,val)
1154            currentLength = length(obj.resample);
1155            new = zeros(1,(val-currentLength));
1156            new = [obj.resample,new];
1157            obj.resample = new;
1158         end
1159
1160         function obj = contractNResample(obj,val)
1161            obj.resample = obj.resample(1:val);
1162         end
1163
1164         function obj = extendNDataPresent(obj,val)
1165            currentLength = length(obj.dataPresent);
1166            new = zeros(1,(val-currentLength));
1167            new = [obj.dataPresent,new];
1168            obj.dataPresent = new;
1169         end
1170
1171         function obj = contractNDataPresent(obj,val)
1172            obj.dataPresent = obj.dataPresent(1:val);
1173         end
1174
1175         function obj = extendNParamNames(obj,val)
1176            currentLength = length(obj.paramNames);
1177            new = cell([1,(val-currentLength)]);
1178            new = horzcat([obj.paramNames],new);
1179            obj.paramNames = new;
1180         end
1181
1182         function obj = contractNParamNames(obj,val)
1183            obj.paramNames = obj.paramNames(1:val);
1184         end
1185
1186         function obj = extendNParamConstr(obj,val)
1187            currentLength = length(obj.paramConstr);
1188            new = cell([1,(val-currentLength)]);
1189            new(:) = {[0 0]};
1190            new = horzcat([obj.paramConstr],new);
1191            obj.paramConstr = new;
1192         end
1193
1194         function obj = contractNParamConstr(obj,val)
1195             obj.paramConstr = obj.paramConstr(1:val);
1196         end
1197
1198         function obj = extendNParamFitYesNo(obj,val)
1199            currentLength = length(obj.paramFitYesNo);
1200            new = zeros(1,(val-currentLength));
1201            new = [obj.paramFitYesNo,new];
1202            obj.paramFitYesNo = new;
1203         end
1204
1205         function obj = contractNParamFitYesNo(obj,val)
1206             obj.paramFitYesNo = obj.paramFitYesNo(1:val);
1207         end
1208
1209
1210      %Backgrounds
1211         function obj = extendNBackgrounds(obj,val)
1212            currentLength = length(obj.backgrounds);
1213            new = zeros(1,(val-currentLength));
1214            new = [obj.backgrounds,new];
1215            obj.backgrounds = new;
1216         end
1217
1218         function obj = contractNBackgrounds(obj,val)
1219            obj.backgrounds = obj.backgrounds(1:val);
1220         end
1221
1222         function obj = extendNBackgroundNames(obj,val)
1223            currentLength = length(obj.backgroundNames);
1224            new = cell([1,(val-currentLength)]);
1225            new = horzcat([obj.backgroundNames],new);
1226            obj.backgroundNames = new;
1227         end
1228
1229         function obj = contractNBackgroundNames(obj,val)
1230            obj.backgroundNames = obj.backgroundNames(1:val);
1231         end
1232
1233         function obj = extendNBackgroundConstr(obj,val)
1234            currentLength = length(obj.backgroundConstr);
1235            new = cell([1,(val-currentLength)]);
1236            new(:) = {[0 0]};
1237            new = horzcat([obj.backgroundConstr],new);
1238            obj.backgroundConstr = new;
1239         end
1240
1241         function obj = contractNBackgroundConstr(obj,val)
1242             obj.backgroundConstr = obj.backgroundConstr(1:val);
1243         end
1244
1245         function obj = extendNBackgroundFitYesNo(obj,val)
1246            currentLength = length(obj.backgroundFitYesNo);
1247            new = zeros(1,(val-currentLength));
1248            new = [obj.backgroundFitYesNo,new];
1249            obj.backgroundFitYesNo = new;
1250         end
1251
1252         function obj = contractNBackgroundFitYesNo(obj,val)
1253             obj.backgroundFitYesNo = obj.backgroundFitYesNo(1:val);
1254         end
1255
1256
1257      %Scalefactors
1258         function obj = extendNScalefactors(obj,val)
1259            currentLength = length(obj.scalefactors);
1260            new = zeros(1,(val-currentLength));
1261            new = [obj.scalefactors,new];
1262            obj.scalefactors = new;
1263         end
1264
1265         function obj = contractNScalefactors(obj,val)
1266            obj.scalefactors = obj.scalefactors(1:val);
1267         end
1268
1269         function obj = extendNScalefactorNames(obj,val)
1270            currentLength = length(obj.scalefactorNames);
1271            new = cell([1,(val-currentLength)]);
1272            new = horzcat([obj.scalefactorNames],new);
1273            obj.scalefactorNames = new;
1274         end
1275
1276         function obj = contractNScalefactorNames(obj,val)
1277            obj.scalefactorNames = obj.scalefactorNames(1:val);
1278         end
1279
1280         function obj = extendNScalefactorConstr(obj,val)
1281            currentLength = length(obj.scalefactorConstr);
1282            new = cell([1,(val-currentLength)]);
1283            new(:) = {[0 0]};
1284            new = horzcat([obj.scalefactorConstr],new);
1285            obj.scalefactorConstr = new;
1286         end
1287
1288         function obj = contractNScalefactorConstr(obj,val)
1289             obj.scalefactorConstr = obj.scalefactorConstr(1:val);
1290         end
1291
1292        function obj = extendNScalefactorFitYesNo(obj,val)
1293            currentLength = length(obj.scalefactorFitYesNo);
1294            new = zeros(1,(val-currentLength));
1295            new = [obj.scalefactorFitYesNo,new];
1296            obj.scalfactorFitYesNo = new;
1297         end
1298
1299         function obj = contractNScalefactorFitYesNo(obj,val)
1300             obj.scalefactorFitYesNo = obj.scalefactorFitYesNo(1:val);
1301         end
1302
1303
1304     %QZ shifts
1305         function obj = extendNQzshifts(obj,val)
1306            currentLength = length(obj.qzshifts);
1307            new = zeros(1,(val-currentLength));
1308            new = [obj.qzshifts,new];
1309            obj.qzshifts = new;
1310         end
1311
1312         function obj = contractNQzshifts(obj,val)
1313            obj.qzshifts = obj.qzshifts(1:val);
1314         end
1315
1316         function obj = extendNQzshiftNames(obj,val)
1317            currentLength = length(obj.qzshiftNames);
1318            new = cell([1,(val-currentLength)]);
1319            new = horzcat([obj.qzshiftNames],new);
1320            obj.qzshiftNames = new;
1321         end
1322
1323         function obj = contractNQzshiftNames(obj,val)
1324            obj.qzshiftNames = obj.qzshiftNames(1:val);
1325         end
1326
1327         function obj = extendNQzshiftConstr(obj,val)
1328            currentLength = length(obj.qzshiftConstr);
1329            new = cell([1,(val-currentLength)]);
1330            new(:) = {[0 0]};
1331            new = horzcat([obj.qzshiftConstr],new);
1332            obj.qzshiftConstr = new;
1333         end
1334
1335         function obj = contractNQzshiftConstr(obj,val)
1336             obj.qzshiftConstr = obj.qzshiftConstr(1:val);
1337         end
1338
1339         function obj = extendNQzshiftFitYesNo(obj,val)
1340            currentLength = length(obj.qzshiftFitYesNo);
1341            new = zeros(1,(val-currentLength));
1342            new = [obj.qzshiftFitYesNo,new];
1343            obj.qzshiftFitYesNo = new;
1344         end
1345
1346         function obj = contractNQzshiftFitYesNo(obj,val)
1347             obj.qzshiftFitYesNo = obj.qzshiftFitYesNo(1:val);
1348         end
1349
1350
1351     %nbairs
1352         function obj = extendNNbairs(obj,val)
1353            currentLength = length(obj.nbairs);
1354            new = zeros(1,(val-currentLength));
1355            new = [obj.nbairs,new];
1356            obj.nbairs = new;
1357         end
1358
1359         function obj = contractNNbairs(obj,val)
1360            obj.nbairs = obj.nbairs(1:val);
1361         end
1362
1363         function obj = extendNNbairNames(obj,val)
1364            currentLength = length(obj.nbairNames);
1365            new = cell([1,(val-currentLength)]);
1366            new = horzcat([obj.nbairNames],new);
1367            obj.nbairNames = new;
1368         end
1369
1370         function obj = contractNNbairNames(obj,val)
1371            obj.nbairNames = obj.nbairNames(1:val);
1372         end
1373
1374         function obj = extendNNbairConstr(obj,val)
1375            currentLength = length(obj.nbairConstr);
1376            new = cell([1,(val-currentLength)]);
1377            new(:) = {[0 0]};
1378            new = horzcat([obj.nbairConstr],new);
1379            obj.nbairConstr = new;
1380         end
1381
1382         function obj = contractNNbairConstr(obj,val)
1383             obj.nbairConstr = obj.nbairConstr(1:val);
1384         end
1385
1386         function obj = extendNNbairFitYesNo(obj,val)
1387            currentLength = length(obj.nbairFitYesNo);
1388            new = zeros(1,(val-currentLength));
1389            new = [obj.nbairFitYesNo,new];
1390            obj.nbairFitYesNo = new;
1391         end
1392
1393         function obj = contractNNbairFitYesNo(obj,val)
1394             obj.nbairFitYesNo = obj.nbairFitYesNo(1:val);
1395         end
1396
1397
1398     %nbsubs
1399         function obj = extendNNbsubs(obj,val)
1400            currentLength = length(obj.nbsubs);
1401            new = zeros(1,(val-currentLength));
1402            new = [obj.nbsubs,new];
1403            obj.nbsubs = new;
1404         end
1405
1406         function obj = contractNNbsubs(obj,val)
1407            obj.nbsubs = obj.nbsubs(1:val);
1408         end
1409
1410         function obj = extendNNbsubNames(obj,val)
1411            currentLength = length(obj.nbsubNames);
1412            new = cell([1,(val-currentLength)]);
1413            new = horzcat([obj.nbsubNames],new);
1414            obj.nbsubNames = new;
1415         end
1416
1417         function obj = contractNNbsubNames(obj,val)
1418            obj.nbsubNames = obj.nbsubNames(1:val);
1419         end
1420
1421         function obj = extendNNbsubConstr(obj,val)
1422            currentLength = length(obj.nbsubConstr);
1423            new = cell([1,(val-currentLength)]);
1424            new(:) = {[0 0]};
1425            new = horzcat([obj.nbsubConstr],new);
1426            obj.nbsubConstr = new;
1427         end
1428
1429         function obj = contractNNbsubConstr(obj,val)
1430             obj.nbsubConstr = obj.nbsubConstr(1:val);
1431         end
1432
1433         function obj = extendNNbsubFitYesNo(obj,val)
1434            currentLength = length(obj.nbsubFitYesNo);
1435            new = zeros(1,(val-currentLength));
1436            new = [obj.nbsubFitYesNo,new];
1437            obj.nbsubFitYesNo = new;
1438         end
1439
1440         function obj = contractNNbsubFitYesNo(obj,val)
1441             obj.nbsubFitYesNo = obj.nbsubFitYesNo(1:val);
1442         end
1443
1444
1445
1446     %Resolutins
1447         function obj = extendNResolutions(obj,val)
1448            currentLength = length(obj.resolutions);
1449            new = zeros(1,(val-currentLength));
1450            new = [obj.resolutins,new];
1451            obj.resolutions = new;
1452         end
1453
1454         function obj = contractNReslutions(obj,val)
1455            obj.resolutions = obj.resolutions(1:val);
1456         end
1457
1458         function obj = extendNResolutionsNames(obj,val)
1459            currentLength = length(obj.resolutionsNames);
1460            new = cell([1,(val-currentLength)]);
1461            new = horzcat([obj.resolutinsNames],new);
1462            obj.reslutionsNames = new;
1463         end
1464
1465         function obj = contractNResolutionsNames(obj,val)
1466            obj.reslutionsNames = obj.resolutionsNames(1:val);
1467         end
1468
1469         function obj = extendNResolutionsConstr(obj,val)
1470            currentLength = length(obj.resolutionsConstr);
1471            new = cell([1,(val-currentLength)]);
1472            new(:) = {[0 0]};
1473            new = horzcat([obj.resolutionsConstr],new);
1474            obj.resolutionsConstr = new;
1475         end
1476
1477         function obj = contractNResolutionConstr(obj,val)
1478             obj.resolutionConstr = obj.resolutionConstr(1:val);
1479         end
1480
1481         function obj = extendNResolutionFitYesNo(obj,val)
1482            currentLength = length(obj.resolutionFitYesNo);
1483            new = zeros(1,(val-currentLength));
1484            new = [obj.resolutionFitYesNo,new];
1485            obj.resolutionFitYesNo = new;
1486         end
1487
1488         function obj = contractNResolutionFitYesNo(obj,val)
1489             obj.resolutionFitYesNo = obj.resolutionFitYesNo(1:val);
1490         end
1491
1492
1493
1494
1495
1496
1497 %--------------------------------------------------------------------------
1498     %Data and contrasts
1499         function obj = extendAllData(obj,val)
1500            currentLength = length(obj.allData);
1501            new = cell([1,(val-currentLength)]);
1502            new(:) = {[]};
1503            new = horzcat([obj.allData],new);
1504            obj.allData = new;
1505         end
1506
1507         function obj = contractAllData(obj,val)
1508             obj.allData = obj.allData(1:val);
1509         end
1510
1511         function obj = extendNDataLimits(obj,val)
1512            currentLength = length(obj.dataLimits);
1513            new = cell([1,(val-currentLength)]);
1514            new(:) = {[0 0]};
1515            new = horzcat([obj.dataLimits],new);
1516            obj.dataLimits = new;
1517         end
1518
1519         function obj = contractNDataLimits(obj,val)
1520             obj.dataLimits = obj.dataLimits(1:val);
1521         end
1522
1523         function obj = extendNSimLimits(obj,val)
1524            currentLength = length(obj.simLimits);
1525            new = cell([1,(val-currentLength)]);
1526            new(:) = {[0 0]};
1527            new = horzcat([obj.simLimits],new);
1528            obj.simLimits = new;
1529         end
1530
1531         function obj = contractNSimLimits(obj,val)
1532             obj.simLimits = obj.simLimits(1:val);
1533         end
1534
1535         function obj = extendNContrastBacks(obj,val)
1536            currentLength = length(obj.contrastBacks);
1537            new = cell([1,(val-currentLength)]);
1538            new(:) = {{0 1}};
1539            new = horzcat([obj.contrastBacks],new);
1540            obj.contrastBacks = new;
1541         end
1542
1543         function obj = contractNContrastBacks(obj,val)
1544             obj.contrastBacks = obj.contrastBacks(1:val);
1545         end
1546
1547         function obj = extendNContrastShifts(obj,val)
1548            currentLength = length(obj.contrastShifts);
1549            new = ones([1,(val-currentLength)]);
1550            new = horzcat([obj.contrastShifts],new);
1551            obj.contrastShifts = new;
1552         end
1553
1554         function obj = contractNContrastShifts(obj,val)
1555             obj.contrastShifts = obj.contrastShifts(1:val);
1556         end
1557
1558         function obj = extendNContrastScales(obj,val)
1559            currentLength = length(obj.contrastScales);
1560            new = ones([1,(val-currentLength)]);
1561            new = horzcat([obj.contrastScales],new);
1562            obj.contrastShifts = new;
1563         end
1564
1565         function obj = contractNContrastScales(obj,val)
1566             obj.contrastScales = obj.contrastScales(1:val);
1567         end
1568
1569         function obj = extendNContrastNbas(obj,val)
1570            currentLength = length(obj.contrastNbas);
1571            new = ones([1,(val-currentLength)]);
1572            new = horzcat([obj.contrastNbas],new);
1573            obj.contrastNbas = new;
1574         end
1575
1576         function obj = contractNContrastNbas(obj,val)
1577             obj.contrastNbas = obj.contrastNbas(1:val);
1578         end
1579
1580         function obj = extendNContrastNbss(obj,val)
1581            currentLength = length(obj.contrastNbss);
1582            new = ones([1,(val-currentLength)]);
1583            new = horzcat([obj.contrastNbss],new);
1584            obj.contrastNbss = new;
1585         end
1586
1587         function obj = contractNContrastNbss(obj,val)
1588             obj.contrastNbss = obj.contrastNbss(1:val);
1589         end
1590
1591         function obj = extendNContrastRes(obj,val)
1592            currentLength = length(obj.contrastRes);
1593            new = ones([1,(val-currentLength)]);
1594            new = horzcat([obj.contrastRes],new);
1595            obj.contrastNbss = new;
1596         end
1597
1598         function obj = contractNContrastRes(obj,val)
1599             obj.contrastRes = obj.contrastRes(1:val);
1600         end
1601
1602         function obj = extendNContrastRepeatSLDs(obj,val)
1603            currentLength = length(obj.contrastRepeatSLDs);
1604            new = cell([1,(val-currentLength)]);
1605            new(:) = {[0 1]};
1606            new = horzcat([obj.contrastRepeatSLDs],new);
1607            obj.contrastRepeatSLDs = new;
1608         end
1609
1610         function obj = contractNContrastRepeatSLDs(obj,val)
1611             obj.contrastRepeatSLDs = obj.contrastRepeatSLDs(1:val);
1612         end
1613 %-----------------------------------------------------------------------
1614 %Model
1615         function obj = extendNLayersDetails(obj,val)
1616             currentLength = size(obj.layersDetails,1);
1617             new = cell((val-currentLength),1);
1618             new(:) = {[1 1 1 0 1]};
1619             new = vercat(obj.layersDetails,new);
1620             obj.layersDetails = new;
1621         end
1622
1623         function obj = extendNContrastLayers(obj,val)
1624            currentLength = length(obj.contrastLayers);
1625            new = cell([1,(val-currentLength)]);
1626            new(:) = {[]};
1627            new = vertcat([obj.contrastLayers],new);
1628            obj.contrastLayers = new;
1629         end
1630
1631         function obj = contractNContrastLayers(obj,val)
1632             obj.contrastLayers = obj.contrastLayers(1:val);
1633         end
1634
1635     end     %End Private Methods
1636
1637 %-------------------------------------------------------------------------
1638
1639 %Display Methods
1640 methods (Access = protected)
1641
1642     function groups = getPropertyGroups(obj)
1643
1644                masterPropList = struct('experimentType', obj.experimentType,...
1645                      'experimentGeometry', obj.experimentGeometry    ,...
1646                      'nParams', obj.nParams,...
1647                      'params', {obj.params},...
1648                      'paramNames', {obj.paramNames},...
1649                      'paramConstr', {obj.paramConstr},...
1650                      'paramFitYesNo', {obj.paramFitYesNo},...
1651                      'nBackgrounds', obj.nBackgrounds,...
1652                      'backgrounds', {obj.backgrounds},...
1653                      'backgroundNames', {obj.backgroundNames},...
1654                      'backgroundConstr', {obj.backgroundConstr},...
1655                      'backgroundFitYesNo',{obj.backgroundFitYesNo},...
1656                      'nScalefactors', obj.nScalefactors,...
1657                      'scalefactors', {obj.scalefactors},...
1658                      'scalefactorNames', {obj.scalefactorNames},...
1659                      'scalefactorConstr', {obj.scalefactorConstr},...
1660                      'scalefactorFitYesNo',{obj.scalefactorFitYesNo},...
1661                      'nQzshifts', obj.nQzshifts,...
1662                      'qzshifts', {obj.qzshifts},...
1663                      'qzshiftNames', {obj.qzshiftNames},...
1664                      'qzshiftConstr', {obj.qzshiftConstr},...
1665                      'qzshiftFitYesNo',{obj.qzshiftFitYesNo},...
1666                      'nNbairs', obj.nNbairs,...
1667                      'nbairs', {obj.nbairs},...
1668                      'nbairNames', {obj.nbairNames},...
1669                      'nbairConstr', {obj.nbairConstr},...
1670                      'nbairFitYesNo',{obj.nbairFitYesNo},...
1671                      'nNbsubs', obj.nNbsubs,...
1672                      'nbsubs', {obj.nbsubs},...
1673                      'nbsubNames', {obj.nbsubNames},...
1674                      'nbsubConstr', {obj.nbsubConstr},...
1675                      'nbsubFitYesNo',{obj.nbsubFitYesNo},...
1676                      'numberOfContrasts', obj.numberOfContrasts,...
1677                      'nResolutions', obj.nResolutions,...
1678                      'resolutions', {obj.resolutions},...
1679                      'resolutionNames', {obj.resolutionNames},...
1680                      'resolutionConstr', {obj.resolutionConstr},...
1681                      'resolutionFitYesNo',{obj.resolutionFitYesNo},...
1682                      'allData', {obj.allData},...
1683                      'dataPresent', {obj.dataPresent},...
1684                      'resample', obj.resample,...
1685                      'dataLimits', {obj.dataLimits},...
1686                      'simLimits', {obj.simLimits},...
1687                      'contrastBacks', {obj.contrastBacks},...
1688                      'contrastShifts', {obj.contrastShifts},...
1689                      'contrastScales', {obj.contrastScales},...
1690                      'contrastNbas', {obj.contrastNbas},...
1691                      'contrastNbss', {obj.contrastNbss},...
1692                      'contrastRes', {obj.contrastRes},...
1693                      'contrastRepeatSLDs', {obj.contrastRepeatSLDs},...
1694                      'modelType', obj.modelType,...
1695                      'numberOfLayers', obj.numberOfLayers,...
1696                      'layersDetails', {obj.layersDetails},...
1697                      'contrastLayers', {obj.contrastLayers},...
1698                      'modelFilename', obj.modelFilename,...
1699                      'modelLanguage', obj.modelLanguage);
1700          if isscalar(obj)
1701                  if strcmpi(obj.experimentGeometry,'substrate/liquid')
1702                      dispPropList = masterPropList;
1703                  elseif strcmpi(obj.experimentGeometry,'air/substrate')
1704                      dispPropList = rmfield(masterPropList,{'nNbairs','nbairs','nbairNames','nbairConstr'});
1705                  end
1706
1707                  if ~strcmpi(obj.modelType,'layers')
1708                      dispPropList = rmfield(dispPropList,{'numberOfLayers','layersDetails','contrastLayers'});
1709                  else
1710                      dispPropList = rmfield(dispPropList,{'modelFilename','modelLanguage'});
1711                  end
1712
1713                  if ~isempty(dispPropList)
1714                      groups = matlab.mixin.util.PropertyGroup(dispPropList);
1715                  else
1716                      groups = matlab.mixin.util.PropertyGroup(masterPropList);
1717                  end
1718         else
1719             groups = getPropertyGroups@matlab.mixin.CustomDisplay(obj);
1720         end
1721
1722
1723
1724     end
1725
1726 end     %End display methods
1727
1728 end     %End ClassDef
1729
1730
1731
1732