%% Simple example of a layer containing domains using a custom XY model

problem = createProject(calcType="domains");
problem.setModelType('custom XY');
problem.setGeometry('substrate/liquid');

% Make some parameters...
params = {{'Oxide thick',   10,         20,         50,     true}
          {'Layer thick',   1,          30,         500,    true}
          {'Layer SLD',     -0.5e-6,    -0.5e-6     0,      true}
          {'Layer rough',   2,          5,          7,      true}
          {'Domain rho ',   1e-6,       1e-6,       5e-6,   true}};

problem.addParameterGroup(params);

% Set the bulk SLD
problem.setBulkIn(1,'name','Silicon','Value',2.073e-6,'max',2.073e-6,'fit',false);

% and scalefactor...
problem.setScalefactor(1,'min',0.8,'Value',1,'max',1.1,'fit',true);

% Add another couple of bulk-out's 
problem.addBulkOut('SLD SMW', 2e-6, 2.073e-6, 2.1e-6);
problem.addBulkOut('SLD H2O', -0.6e-6, -0.56e-6, -0.5e-6);

% Add the custom file...
problem.addCustomFile('Domain Layer','domainsXY.m','matlab',pwd);

% Make a contrast
problem.addContrast('name',         'D2O',...
                    'background',   'Background 1',...
                    'resolution',   'Resolution 1',...
                    'scalefactor',  'Scalefactor 1',...
                    'Bulkin',       'Silicon',...       
                    'Bulkout',      'SLD D2O',....           
                    'domainRatio',  'Domain Ratio 1',...
                    'data',         'Simulation');

problem.addContrast('name',         'SMW',...
                    'background',   'Background 1',...
                    'resolution',   'Resolution 1',...
                    'scalefactor',  'Scalefactor 1',...
                    'Bulkin',       'Silicon',...       
                    'Bulkout',      'SLD SMW',....           
                    'domainRatio',  'Domain Ratio 1',...
                    'data',         'Simulation');

problem.addContrast('name',         'H2O',...
                    'background',   'Background 1',...
                    'resolution',   'Resolution 1',...
                    'scalefactor',  'Scalefactor 1',...
                    'Bulkin',       'Silicon',...       
                    'Bulkout',      'SLD H2O',....           
                    'domainRatio',  'Domain Ratio 1',...
                    'data',         'Simulation');

% Set the model to our custom file...
for i = 1:3
    problem.setContrastModel(i,'Domain Layer');
end



