Description of getpar
getpar
PURPOSE
GETPAR get parameter value from a struct
SYNOPSIS
function y=getpar(options,par,default)
DESCRIPTION
GETPAR get parameter value from a struct
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
mcmcrun MCMCRUN Metropolis-Hastings MCMC simulation for nonlinear Gaussian models
mcmcrun_compile MCMCRUN Metropolis-Hastings MCMC simulation for nonlinear Gaussian models
mcmcrun MCMCRUN Metropolis-Hastings MCMC simulation for nonlinear Gaussian models
SOURCE CODE
function y=getpar(options,par,default)
%GETPAR get parameter value from a struct
% $Revision: 1.1 $  $Date: 2005/02/11 13:24:53 $
if isfield(options,par)
    y = getfield(options,par);
else
    y = default;
end
% defaults = {
%     {'nsimu'} , {1000}
%     {'doadapt'}, {0}
%            };
%
% if isfield(options,par)
%   y = getfield(options,par);
% elseif nargin>2
%   y = default;
% else
%   for i = 1:size(defaults,1)
%     if strcmp(defaults{i,1},par)
%       y = defaults{i,2};
%       return
%     end
%   end
%   error(sprintf('no default value for %s defined',par));
end