Description of sendTextOutput
sendTextOutput
PURPOSE
SYNOPSIS
function sendTextOutput(text)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
outputClass
This function is called by:
RAT
RATMain
SOURCE CODE
function sendTextOutput(text)
persistent ratOut
if isempty(ratOut)
    ratOut = getappdata(0,'ratOut');
    outputClass = ratOut{1};
end
try
    outputClass.customEventData.textUpdate = text;
    outputClass.triggerEvent;
catch
    disp(text);
end