Description of chiSquared
chiSquared
PURPOSE
Chi-squared function is used to evaluate the goodness of fit.
SYNOPSIS
function chi2 = chiSquared(thisData,thisFit,P)
DESCRIPTION
 Chi-squared function is used to evaluate the goodness of fit.
 It is a measure of the difference between the observed and expected.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
domainsTFCustomLayersParallelContrasts Single threaded version of the custom layers, domainsTF reflectivity
domainsTFCustomLayersParallelPoints Single threaded version of the custom layers, domainsTF reflectivity
domainsTFCustomLayersSingle Single threaded version of the custom layers, domainsTF reflectivity
domainsTFCustomXYParallelContrasts Extract individual cell arrays
domainsTFCustomXYParallelPoints Extract individual cell arrays
domainsTFCustomXYSingle Extract individual cell arrays
domainsTFStandardLayersParallelContrasts Single threaded version of the Standard Layers calculation
domainsTFStandardLayersParallelPoints Single threaded version of the Standard Layers calculation
domainsTFStandardLayersSingle Single threaded version of the Standard Layers calculation
standardTFCustomXYParallelContrasts Extract individual cell arrays
standardTFCustomXYParallelPoints Multi threaded version of the custom XY profile over reflectivity points
standardTFCustomXYSingle Extract individual cell arrays
standardTFLayersCore This is the main reflectivity calculation for all Layers models in the
SOURCE CODE
function chi2 = chiSquared(thisData,thisFit,P)
% Chi-squared function is used to evaluate the goodness of fit.
% It is a measure of the difference between the observed and expected.
%allChis = zeros(1,numberOfContrasts);
%     thisData = allData{i};
%     thisFit = allFits{i};
    y = thisData(:,2);
    eb = thisData(:,3);
    fit = thisFit(:,2);
    N = max(size(y));
    if N <= P
        N = (P + 1);
    end
    terms = ((y-fit)./eb).^2;
    n = find(terms == Inf);
    if ~isempty(n)
        terms(n) = 0;
    end
    chi2 = 1/(N-P)*sum(terms);
    %allChis(i) = chi2;
end