Description of callMatlabFunction
callMatlabFunction
PURPOSE
Excecute a custom model function in the base Matlab workspace.
SYNOPSIS
function [output,sRough] = callMatlabFunction(params, contrast, funcName, bulkIn, bulkOut, nContrasts, domainNumber)
DESCRIPTION
 Excecute a custom model function in the base Matlab workspace.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
processCustomFunction Top-level function for processing custom layers for all the
processCustomFunction Top-level function for processing custom XY profiles for all the
processCustomFunction Top-level function for processing custom layers for all the
processCustomFunction Top-level function for processing custom XY profiles for all the
SOURCE CODE
function [output,sRough] = callMatlabFunction(params, contrast, funcName, bulkIn, bulkOut, nContrasts, domainNumber)
% Excecute a custom model function in the base Matlab workspace.
if coder.target('MATLAB')
    % For backwards compatability with Rascal1...
    bulkOuts = zeros(nContrasts,1);
    bulkOuts(contrast) = bulkOut;
    fileHandle = str2func(funcName);
    if (domainNumber < 1)
        [output,sRough] = fileHandle(params,bulkIn,bulkOuts,contrast);
    else
        [output,sRough] = fileHandle(params,bulkIn,bulkOuts,contrast,domainNumber);
    end
elseif coder.target('MEX')
    bulkOuts = zeros(nContrasts,1);
    bulkOuts(contrast) = bulkOut;
    % 'feval' generates an automatic coder.extrinsic call.
    if (domainNumber < 1)
        [output,sRough] = feval(funcName, params, bulkIn, bulkOuts, contrast);
    else
        [output,sRough] = feval(funcName, params, bulkIn, bulkOuts, contrast, domainNumber);
    end
else
    % Calling matlab from other languages should be implemented in their wrapper
    sRough = 0;
    output = zeros([0 0]);
    error("This is not supported!");
end