Description of applyBackgroundCorrection
applyBackgroundCorrection
PURPOSE
SYNOPSIS
function [reflect,Simul,shifted_dat] = applyBackgroundCorrection(reflect,Simul,shifted_dat,backg,backsType)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
domainsTFCustomXYParallelContrasts Extract individual cell arrays
domainsTFCustomXYParallelPoints Extract individual cell arrays
domainsTFCustomXYSingle Extract individual cell arrays
standardTFCustomXYParallelContrasts Extract individual cell arrays
standardTFCustomXYParallelPoints Multi threaded version of the custom XY profile over reflectivity points
standardTFCustomXYSingle Extract individual cell arrays
standardTFLayersCore This is the main reflectivity calculation for all Layers models in the
SOURCE CODE
function    [reflect,Simul,shifted_dat] = applyBackgroundCorrection(reflect,Simul,shifted_dat,backg,backsType)
switch backsType
    case 1
        %Add background to the simulation
        reflect(:,2) = reflect(:,2) + backg;
        Simul(:,2) = Simul(:,2) + backg;
     case 2
%         %Subtract the background from the data..
        shifted_dat(:,2) = shifted_dat(:,2) - backg;
        %shifted_dat(:,3) = shifted_dat(:,3) - backg;
 end
end