Description of getnbatch
getnbatch
PURPOSE
try to guess number of batches of mcmc data
SYNOPSIS
function n=getnbatch(data)
DESCRIPTION
 try to guess number of batches of mcmc data
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
mcmcrun MCMCRUN Metropolis-Hastings MCMC simulation for nonlinear Gaussian models
mcmcrun_compile MCMCRUN Metropolis-Hastings MCMC simulation for nonlinear Gaussian models
mcmcssfun MCMCSSFUN general Gaussian sum of squares function for mcmcrun
mcmcrun MCMCRUN Metropolis-Hastings MCMC simulation for nonlinear Gaussian models
mcmcssfun MCMCSSFUN general Gaussian sum of squares function for mcmcrun
SOURCE CODE
function n=getnbatch(data)
% try to guess number of batches of mcmc data
% $Revision: 1.2 $  $Date: 2005/09/12 11:04:52 $
if isnumeric(data)
  n = 1;
elseif iscell(data)
  n = length(data);
elseif isstruct(data)
  if isfield(data,'ydata')
    if iscell(data.ydata)
      n = length(data.ydata);
    else
      n = 1;
    end
  else
    n = [];
  end
else
  n = [];
end